CREATE TABLE [logging].[orderdetail] (
    [Instance]        INT            IDENTITY (1, 1) NOT NULL,
    [ChangeDate]      DATETIME       NULL,
    [HostName]        VARCHAR (50)   NULL,
    [ServerName]      VARCHAR (50)   NULL,
    [UserName]        VARCHAR (50)   NULL,
    [Actions]         VARCHAR (50)   NULL,
    [OrderDetailId]   INT            NOT NULL,
    [OrderDetailType] VARCHAR (1)    NULL,
    [OrderId]         INT            NULL,
    [GroupNumber]     INT            NULL,
    [GroupName]       NVARCHAR (50)  NULL,
    [ProductId]       INT            NULL,
    [GersSku]         VARCHAR (9)    NULL,
    [ProductTitle]    VARCHAR (500)  NULL,
    [PartNumber]      NVARCHAR (50)  NULL,
    [Qty]             INT            NULL,
    [COGS]            MONEY          NULL,
    [RetailPrice]     MONEY          NULL,
    [NetPrice]        MONEY          NULL,
    [Weight]          FLOAT (53)     NULL,
    [TotalWeight]     INT            NULL,
    [Taxable]         BIT            NULL,
    [Taxes]           MONEY          NULL,
    [Message]         NVARCHAR (255) NULL,
    [ShipmentId]      INT            NULL,
    [RMANumber]       VARCHAR (50)   NULL,
    [RMAStatus]       INT            NULL,
    [RMAReason]       VARCHAR (50)   NULL,
    [Rebate]          MONEY          NULL,
    [DiscountTotal]   MONEY          NULL,
    PRIMARY KEY CLUSTERED ([Instance] ASC)
);

