//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace WirelessAdvocate.CarrierServices.Proxies.Sprint.PreAuthorization {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("fault", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class OVMFault {
        
        private ErrorInfo[] detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("errorInfo", IsNullable=false)]
        public ErrorInfo[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class ErrorInfo {
        
        private uint errortypeField;
        
        private string errorcodeField;
        
        private string errorsubnameField;
        
        private string errordetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-type")]
        public uint errortype {
            get {
                return this.errortypeField;
            }
            set {
                this.errortypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", DataType="integer")]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-sub-name")]
        public string errorsubname {
            get {
                return this.errorsubnameField;
            }
            set {
                this.errorsubnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-details")]
        public string errordetails {
            get {
                return this.errordetailsField;
            }
            set {
                this.errordetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class Address {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("city", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("clone-address", typeof(CloneAddressType))]
        [System.Xml.Serialization.XmlElementAttribute("country-code", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("state-code", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("street-address-1", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("street-address-2", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("update-address", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("zip-code", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum CloneAddressType {
        
        /// <remarks/>
        SAME_AS_BILLING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        city,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("clone-address")]
        cloneaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("country-code")]
        countrycode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("state-code")]
        statecode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("street-address-1")]
        streetaddress1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("street-address-2")]
        streetaddress2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("update-address")]
        updateaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("zip-code")]
        zipcode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class CreditCard {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address", typeof(Address))]
        [System.Xml.Serialization.XmlElementAttribute("card-handle", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("clone-credit-card", typeof(CloneCreditCardType))]
        [System.Xml.Serialization.XmlElementAttribute("expiration", typeof(string), DataType="gYearMonth")]
        [System.Xml.Serialization.XmlElementAttribute("ignore-address-errors", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("number", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("security-code", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("type", typeof(CreditCardType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum CloneCreditCardType {
        
        /// <remarks/>
        SAME_AS_DEPOSIT,
        
        /// <remarks/>
        SAME_AS_EQUIPMENT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum CreditCardType {
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        DC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        address,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("card-handle")]
        cardhandle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("clone-credit-card")]
        clonecreditcard,
        
        /// <remarks/>
        expiration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ignore-address-errors")]
        ignoreaddresserrors,
        
        /// <remarks/>
        number,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("security-code")]
        securitycode,
        
        /// <remarks/>
        type,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("requestHeader", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class RequestMessageHeader {
        
        private string pinField;
        
        private string vendorcodeField;
        
        private string subvendorcodeField;
        
        private string vendorusernameField;
        
        private string vendorpasswordField;
        
        private string messageidField;
        
        private string orderidField;
        
        private RequestMessageType messagetypeField;
        
        private System.DateTime timestampField;
        
        private string returnurlField;
        
        private string resendnumberField;
        
        private BrandType brandtypeField;
        
        private bool brandtypeFieldSpecified;
        
        private string storeidField;
        
        private string associateidField;
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-code")]
        public string vendorcode {
            get {
                return this.vendorcodeField;
            }
            set {
                this.vendorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sub-vendor-code")]
        public string subvendorcode {
            get {
                return this.subvendorcodeField;
            }
            set {
                this.subvendorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-username")]
        public string vendorusername {
            get {
                return this.vendorusernameField;
            }
            set {
                this.vendorusernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-password")]
        public string vendorpassword {
            get {
                return this.vendorpasswordField;
            }
            set {
                this.vendorpasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-id")]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-type")]
        public RequestMessageType messagetype {
            get {
                return this.messagetypeField;
            }
            set {
                this.messagetypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("return-url", DataType="anyURI")]
        public string returnurl {
            get {
                return this.returnurlField;
            }
            set {
                this.returnurlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resend-number", DataType="nonNegativeInteger")]
        public string resendnumber {
            get {
                return this.resendnumberField;
            }
            set {
                this.resendnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-type")]
        public BrandType brandtype {
            get {
                return this.brandtypeField;
            }
            set {
                this.brandtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brandtypeSpecified {
            get {
                return this.brandtypeFieldSpecified;
            }
            set {
                this.brandtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("store-id")]
        public string storeid {
            get {
                return this.storeidField;
            }
            set {
                this.storeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associate-id")]
        public string associateid {
            get {
                return this.associateidField;
            }
            set {
                this.associateidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum RequestMessageType {
        
        /// <remarks/>
        ACTIVATION_REQUEST,
        
        /// <remarks/>
        ACTIVATE_NOW_REQUEST,
        
        /// <remarks/>
        CREDIT_CHECK_REQUEST,
        
        /// <remarks/>
        DEACTIVATION_REQUEST,
        
        /// <remarks/>
        PORT_ELIGIBILITY_REQUEST,
        
        /// <remarks/>
        VALIDATION_REQUEST,
        
        /// <remarks/>
        PORT_STATUS_REQUEST,
        
        /// <remarks/>
        NPA_NXX_REQUEST,
        
        /// <remarks/>
        ACCOUNT_VALIDATION_REQUEST,
        
        /// <remarks/>
        CREDIT_CANCEL_REQUEST,
        
        /// <remarks/>
        PRE_AUTHORIZATION_REQUEST,
        
        /// <remarks/>
        PLANS_REQUEST,
        
        /// <remarks/>
        OPTIONS_REQUEST,
        
        /// <remarks/>
        BILL_SUMMARY_REQUEST,
        
        /// <remarks/>
        SERVICE_VALIDATION_REQUEST,
        
        /// <remarks/>
        SECURITY_QUESTION_REQUEST,
        
        /// <remarks/>
        INVENTORY_CHECK_REQUEST,
        
        /// <remarks/>
        AUTHENTICATE_RESEND_PIN_REQUEST,
        
        /// <remarks/>
        COVERAGE_CHECK_REQUEST,
        
        /// <remarks/>
        CORPORATE_DISCOUNT_REQUEST,
        
        /// <remarks/>
        ACTIVATE_RESERVED_DEVICE_REQUEST,
        
        /// <remarks/>
        DEVICE_INFO_REQUEST,
        
        /// <remarks/>
        ORDER_STATUS_REQUEST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum BrandType {
        
        /// <remarks/>
        NX,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        HB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("responseHeader", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class ResponseMessageHeader {
        
        private string vendorcodeField;
        
        private string messageidField;
        
        private string orderidField;
        
        private ResponseMessageType messagetypeField;
        
        private System.DateTime timestampField;
        
        private string resendnumberField;
        
        private ResponseMessageHeaderBrandtype brandtypeField;
        
        private bool brandtypeFieldSpecified;
        
        private string storeidField;
        
        private string associateidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-code")]
        public string vendorcode {
            get {
                return this.vendorcodeField;
            }
            set {
                this.vendorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-id")]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-type")]
        public ResponseMessageType messagetype {
            get {
                return this.messagetypeField;
            }
            set {
                this.messagetypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resend-number", DataType="nonNegativeInteger")]
        public string resendnumber {
            get {
                return this.resendnumberField;
            }
            set {
                this.resendnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-type")]
        public ResponseMessageHeaderBrandtype brandtype {
            get {
                return this.brandtypeField;
            }
            set {
                this.brandtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brandtypeSpecified {
            get {
                return this.brandtypeFieldSpecified;
            }
            set {
                this.brandtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("store-id")]
        public string storeid {
            get {
                return this.storeidField;
            }
            set {
                this.storeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associate-id")]
        public string associateid {
            get {
                return this.associateidField;
            }
            set {
                this.associateidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum ResponseMessageType {
        
        /// <remarks/>
        ACTIVATION_RESPONSE,
        
        /// <remarks/>
        ACTIVATE_NOW_RESPONSE,
        
        /// <remarks/>
        CREDIT_CHECK_RESPONSE,
        
        /// <remarks/>
        DEACTIVATION_RESPONSE,
        
        /// <remarks/>
        PARSE_RESPONSE,
        
        /// <remarks/>
        CANCELLED_RESPONSE,
        
        /// <remarks/>
        STATUS_RESPONSE,
        
        /// <remarks/>
        PORT_ELIGIBILITY_RESPONSE,
        
        /// <remarks/>
        VALIDATION_RESPONSE,
        
        /// <remarks/>
        PORT_STATUS_RESPONSE,
        
        /// <remarks/>
        NPA_NXX_RESPONSE,
        
        /// <remarks/>
        ACCOUNT_VALIDATION_RESPONSE,
        
        /// <remarks/>
        CREDIT_CANCEL_RESPONSE,
        
        /// <remarks/>
        PRE_AUTHORIZATION_RESPONSE,
        
        /// <remarks/>
        PLANS_RESPONSE,
        
        /// <remarks/>
        OPTIONS_RESPONSE,
        
        /// <remarks/>
        BILL_SUMMARY_RESPONSE,
        
        /// <remarks/>
        SERVICE_VALIDATION_RESPONSE,
        
        /// <remarks/>
        SECURITY_QUESTION_RESPONSE,
        
        /// <remarks/>
        INVENTORY_CHECK_RESPONSE,
        
        /// <remarks/>
        AUTHENTICATE_RESEND_PIN_RESPONSE,
        
        /// <remarks/>
        COVERAGE_CHECK_RESPONSE,
        
        /// <remarks/>
        CORPORATE_DISCOUNT_RESPONSE,
        
        /// <remarks/>
        ACTIVATE_RESERVED_DEVICE_RESPONSE,
        
        /// <remarks/>
        DEVICE_INFO_RESPONSE,
        
        /// <remarks/>
        ORDER_STATUS_RESPONSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nextel.com/ovm")]
    public enum ResponseMessageHeaderBrandtype {
        
        /// <remarks/>
        NX,
        
        /// <remarks/>
        SP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("ackResponse", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class ParseResponse {
        
        private ParseResponseType parseresultField;
        
        private string detailsField;
        
        private string sprintorderidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parse-result")]
        public ParseResponseType parseresult {
            get {
                return this.parseresultField;
            }
            set {
                this.parseresultField = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sprint-order-id")]
        public string sprintorderid {
            get {
                return this.sprintorderidField;
            }
            set {
                this.sprintorderidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum ParseResponseType {
        
        /// <remarks/>
        ACK,
        
        /// <remarks/>
        NACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("doPreAuthorization", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class PreAuthorizationRequest {
        
        private object itemField;
        
        private byte handsetcountField;
        
        private bool handsetcountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cash-deposit", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("deposit-payment", typeof(CreditCard))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("handset-count")]
        public byte handsetcount {
            get {
                return this.handsetcountField;
            }
            set {
                this.handsetcountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool handsetcountSpecified {
            get {
                return this.handsetcountFieldSpecified;
            }
            set {
                this.handsetcountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("doPreAuthorizationResponse", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class PreAuthorizationResponse {
        
        private bool successField;
        
        private string preauthorizationcodeField;
        
        private string detailsField;
        
        private decimal totaldepositField;
        
        private bool totaldepositFieldSpecified;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pre-authorization-code")]
        public string preauthorizationcode {
            get {
                return this.preauthorizationcodeField;
            }
            set {
                this.preauthorizationcodeField = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-deposit")]
        public decimal totaldeposit {
            get {
                return this.totaldepositField;
            }
            set {
                this.totaldepositField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totaldepositSpecified {
            get {
                return this.totaldepositFieldSpecified;
            }
            set {
                this.totaldepositFieldSpecified = value;
            }
        }
    }
}
