//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace WirelessAdvocate.CarrierServices.Proxies.Sprint.BillSumary {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("fault", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class OVMFault {
        
        private ErrorInfo[] detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("errorInfo", IsNullable=false)]
        public ErrorInfo[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class ErrorInfo {
        
        private uint errortypeField;
        
        private string errorcodeField;
        
        private string errorsubnameField;
        
        private string errordetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-type")]
        public uint errortype {
            get {
                return this.errortypeField;
            }
            set {
                this.errortypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", DataType="integer")]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-sub-name")]
        public string errorsubname {
            get {
                return this.errorsubnameField;
            }
            set {
                this.errorsubnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-details")]
        public string errordetails {
            get {
                return this.errordetailsField;
            }
            set {
                this.errordetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class AccountBillList {
        
        private SubscriberAccountCharge[] accountchargelistField;
        
        private SubscriberAccountAdjustment[] accountadjustmentlistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("account-charge-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("account-charge", IsNullable=false)]
        public SubscriberAccountCharge[] accountchargelist {
            get {
                return this.accountchargelistField;
            }
            set {
                this.accountchargelistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("account-adjustment-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("account-adjustment", IsNullable=false)]
        public SubscriberAccountAdjustment[] accountadjustmentlist {
            get {
                return this.accountadjustmentlistField;
            }
            set {
                this.accountadjustmentlistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class SubscriberAccountCharge {
        
        private string soccodeField;
        
        private string descriptionField;
        
        private decimal amountField;
        
        private decimal taxField;
        
        private decimal totalField;
        
        private string fromdateField;
        
        private string todateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("soc-code")]
        public string soccode {
            get {
                return this.soccodeField;
            }
            set {
                this.soccodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("from-date")]
        public string fromdate {
            get {
                return this.fromdateField;
            }
            set {
                this.fromdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("to-date")]
        public string todate {
            get {
                return this.todateField;
            }
            set {
                this.todateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class SubscriberAccountAdjustment {
        
        private string adjustmentreasonField;
        
        private decimal amountField;
        
        private decimal taxField;
        
        private decimal totalField;
        
        private string fromdateField;
        
        private string todateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adjustment-reason")]
        public string adjustmentreason {
            get {
                return this.adjustmentreasonField;
            }
            set {
                this.adjustmentreasonField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("from-date")]
        public string fromdate {
            get {
                return this.fromdateField;
            }
            set {
                this.fromdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("to-date")]
        public string todate {
            get {
                return this.todateField;
            }
            set {
                this.todateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class BillEstimateData {
        
        private decimal totalaccountchargesField;
        
        private decimal totalaccountpaymentsField;
        
        private bool totalaccountpaymentsFieldSpecified;
        
        private decimal totalaccountadjustmentsField;
        
        private bool totalaccountadjustmentsFieldSpecified;
        
        private decimal totalaccountusagechangesField;
        
        private bool totalaccountusagechangesFieldSpecified;
        
        private decimal lastmonthbilltotalField;
        
        private bool lastmonthbilltotalFieldSpecified;
        
        private decimal nextmonthbilltotalField;
        
        private string billstartdateField;
        
        private string billenddateField;
        
        private SubscriberBillListSubscriberbillinfo[] subscriberbilllistField;
        
        private AccountBillList accountbilllistField;
        
        private BillType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-account-charges")]
        public decimal totalaccountcharges {
            get {
                return this.totalaccountchargesField;
            }
            set {
                this.totalaccountchargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-account-payments")]
        public decimal totalaccountpayments {
            get {
                return this.totalaccountpaymentsField;
            }
            set {
                this.totalaccountpaymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalaccountpaymentsSpecified {
            get {
                return this.totalaccountpaymentsFieldSpecified;
            }
            set {
                this.totalaccountpaymentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-account-adjustments")]
        public decimal totalaccountadjustments {
            get {
                return this.totalaccountadjustmentsField;
            }
            set {
                this.totalaccountadjustmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalaccountadjustmentsSpecified {
            get {
                return this.totalaccountadjustmentsFieldSpecified;
            }
            set {
                this.totalaccountadjustmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-account-usage-changes")]
        public decimal totalaccountusagechanges {
            get {
                return this.totalaccountusagechangesField;
            }
            set {
                this.totalaccountusagechangesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalaccountusagechangesSpecified {
            get {
                return this.totalaccountusagechangesFieldSpecified;
            }
            set {
                this.totalaccountusagechangesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-month-bill-total")]
        public decimal lastmonthbilltotal {
            get {
                return this.lastmonthbilltotalField;
            }
            set {
                this.lastmonthbilltotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastmonthbilltotalSpecified {
            get {
                return this.lastmonthbilltotalFieldSpecified;
            }
            set {
                this.lastmonthbilltotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("next-month-bill-total")]
        public decimal nextmonthbilltotal {
            get {
                return this.nextmonthbilltotalField;
            }
            set {
                this.nextmonthbilltotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bill-start-date")]
        public string billstartdate {
            get {
                return this.billstartdateField;
            }
            set {
                this.billstartdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bill-end-date")]
        public string billenddate {
            get {
                return this.billenddateField;
            }
            set {
                this.billenddateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("subscriber-bill-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("subscriber-bill-info", IsNullable=false)]
        public SubscriberBillListSubscriberbillinfo[] subscriberbilllist {
            get {
                return this.subscriberbilllistField;
            }
            set {
                this.subscriberbilllistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("account-bill-list")]
        public AccountBillList accountbilllist {
            get {
                return this.accountbilllistField;
            }
            set {
                this.accountbilllistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BillType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nextel.com/ovm")]
    public partial class SubscriberBillListSubscriberbillinfo {
        
        private string referenceptnField;
        
        private string subscribernoField;
        
        private SubscriberAccountCharge[] subscriberchargelistField;
        
        private SubscriberAccountAdjustment[] subscriberadjustmentlistField;
        
        private SubscriberUsageChargeListSubscriberusagecharge[] subscriberusagechargelistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference-ptn")]
        public string referenceptn {
            get {
                return this.referenceptnField;
            }
            set {
                this.referenceptnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subscriber-no")]
        public string subscriberno {
            get {
                return this.subscribernoField;
            }
            set {
                this.subscribernoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("subscriber-charge-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("subscriber-charge", IsNullable=false)]
        public SubscriberAccountCharge[] subscriberchargelist {
            get {
                return this.subscriberchargelistField;
            }
            set {
                this.subscriberchargelistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("subscriber-adjustment-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("subscriber-adjustment", IsNullable=false)]
        public SubscriberAccountAdjustment[] subscriberadjustmentlist {
            get {
                return this.subscriberadjustmentlistField;
            }
            set {
                this.subscriberadjustmentlistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("subscriber-usage-charge-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("subscriber-usage-charge", IsNullable=false)]
        public SubscriberUsageChargeListSubscriberusagecharge[] subscriberusagechargelist {
            get {
                return this.subscriberusagechargelistField;
            }
            set {
                this.subscriberusagechargelistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nextel.com/ovm")]
    public partial class SubscriberUsageChargeListSubscriberusagecharge {
        
        private decimal usagechargeField;
        
        private decimal taxField;
        
        private decimal totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usage-charge")]
        public decimal usagecharge {
            get {
                return this.usagechargeField;
            }
            set {
                this.usagechargeField = value;
            }
        }
        
        /// <remarks/>
        public decimal tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum BillType {
        
        /// <remarks/>
        FIRST,
        
        /// <remarks/>
        SECOND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class AffinityAttribute {
        
        private string attributecodeField;
        
        private string attributevalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute-code")]
        public string attributecode {
            get {
                return this.attributecodeField;
            }
            set {
                this.attributecodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute-value")]
        public string attributevalue {
            get {
                return this.attributevalueField;
            }
            set {
                this.attributevalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class Feature {
        
        private string[] phonenumberorrangeField;
        
        private System.DateTime expirationdateField;
        
        private bool expirationdateFieldSpecified;
        
        private AffinityAttribute[] affinityField;
        
        private string featureorderkeyField;
        
        private string featurecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number-or-range", DataType="token")]
        public string[] phonenumberorrange {
            get {
                return this.phonenumberorrangeField;
            }
            set {
                this.phonenumberorrangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expiration-date")]
        public System.DateTime expirationdate {
            get {
                return this.expirationdateField;
            }
            set {
                this.expirationdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationdateSpecified {
            get {
                return this.expirationdateFieldSpecified;
            }
            set {
                this.expirationdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("affinity-attribute", IsNullable=false)]
        public AffinityAttribute[] affinity {
            get {
                return this.affinityField;
            }
            set {
                this.affinityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature-order-key")]
        public string featureorderkey {
            get {
                return this.featureorderkeyField;
            }
            set {
                this.featureorderkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("feature-code")]
        public string featurecode {
            get {
                return this.featurecodeField;
            }
            set {
                this.featurecodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public partial class BillSummaryPlan {
        
        private string codeField;
        
        private Feature[] featureField;
        
        private string subscribercountField;
        
        private string idField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature")]
        public Feature[] feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subscriber-count", DataType="positiveInteger")]
        public string subscribercount {
            get {
                return this.subscribercountField;
            }
            set {
                this.subscribercountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("requestHeader", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class RequestMessageHeader {
        
        private string pinField;
        
        private string vendorcodeField;
        
        private string subvendorcodeField;
        
        private string vendorusernameField;
        
        private string vendorpasswordField;
        
        private string messageidField;
        
        private string orderidField;
        
        private RequestMessageType messagetypeField;
        
        private System.DateTime timestampField;
        
        private string returnurlField;
        
        private string resendnumberField;
        
        private BrandType brandtypeField;
        
        private bool brandtypeFieldSpecified;
        
        private string storeidField;
        
        private string associateidField;
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-code")]
        public string vendorcode {
            get {
                return this.vendorcodeField;
            }
            set {
                this.vendorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sub-vendor-code")]
        public string subvendorcode {
            get {
                return this.subvendorcodeField;
            }
            set {
                this.subvendorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-username")]
        public string vendorusername {
            get {
                return this.vendorusernameField;
            }
            set {
                this.vendorusernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-password")]
        public string vendorpassword {
            get {
                return this.vendorpasswordField;
            }
            set {
                this.vendorpasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-id")]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-type")]
        public RequestMessageType messagetype {
            get {
                return this.messagetypeField;
            }
            set {
                this.messagetypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("return-url", DataType="anyURI")]
        public string returnurl {
            get {
                return this.returnurlField;
            }
            set {
                this.returnurlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resend-number", DataType="nonNegativeInteger")]
        public string resendnumber {
            get {
                return this.resendnumberField;
            }
            set {
                this.resendnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-type")]
        public BrandType brandtype {
            get {
                return this.brandtypeField;
            }
            set {
                this.brandtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brandtypeSpecified {
            get {
                return this.brandtypeFieldSpecified;
            }
            set {
                this.brandtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("store-id")]
        public string storeid {
            get {
                return this.storeidField;
            }
            set {
                this.storeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associate-id")]
        public string associateid {
            get {
                return this.associateidField;
            }
            set {
                this.associateidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum RequestMessageType {
        
        /// <remarks/>
        ACTIVATION_REQUEST,
        
        /// <remarks/>
        ACTIVATE_NOW_REQUEST,
        
        /// <remarks/>
        CREDIT_CHECK_REQUEST,
        
        /// <remarks/>
        DEACTIVATION_REQUEST,
        
        /// <remarks/>
        PORT_ELIGIBILITY_REQUEST,
        
        /// <remarks/>
        VALIDATION_REQUEST,
        
        /// <remarks/>
        PORT_STATUS_REQUEST,
        
        /// <remarks/>
        NPA_NXX_REQUEST,
        
        /// <remarks/>
        ACCOUNT_VALIDATION_REQUEST,
        
        /// <remarks/>
        CREDIT_CANCEL_REQUEST,
        
        /// <remarks/>
        PRE_AUTHORIZATION_REQUEST,
        
        /// <remarks/>
        PLANS_REQUEST,
        
        /// <remarks/>
        OPTIONS_REQUEST,
        
        /// <remarks/>
        BILL_SUMMARY_REQUEST,
        
        /// <remarks/>
        SERVICE_VALIDATION_REQUEST,
        
        /// <remarks/>
        SECURITY_QUESTION_REQUEST,
        
        /// <remarks/>
        INVENTORY_CHECK_REQUEST,
        
        /// <remarks/>
        AUTHENTICATE_RESEND_PIN_REQUEST,
        
        /// <remarks/>
        COVERAGE_CHECK_REQUEST,
        
        /// <remarks/>
        CORPORATE_DISCOUNT_REQUEST,
        
        /// <remarks/>
        ACTIVATE_RESERVED_DEVICE_REQUEST,
        
        /// <remarks/>
        DEVICE_INFO_REQUEST,
        
        /// <remarks/>
        ORDER_STATUS_REQUEST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum BrandType {
        
        /// <remarks/>
        NX,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        HB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("responseHeader", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class ResponseMessageHeader {
        
        private string vendorcodeField;
        
        private string messageidField;
        
        private string orderidField;
        
        private ResponseMessageType messagetypeField;
        
        private System.DateTime timestampField;
        
        private string resendnumberField;
        
        private ResponseMessageHeaderBrandtype brandtypeField;
        
        private bool brandtypeFieldSpecified;
        
        private string storeidField;
        
        private string associateidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-code")]
        public string vendorcode {
            get {
                return this.vendorcodeField;
            }
            set {
                this.vendorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-id")]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-type")]
        public ResponseMessageType messagetype {
            get {
                return this.messagetypeField;
            }
            set {
                this.messagetypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resend-number", DataType="nonNegativeInteger")]
        public string resendnumber {
            get {
                return this.resendnumberField;
            }
            set {
                this.resendnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-type")]
        public ResponseMessageHeaderBrandtype brandtype {
            get {
                return this.brandtypeField;
            }
            set {
                this.brandtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brandtypeSpecified {
            get {
                return this.brandtypeFieldSpecified;
            }
            set {
                this.brandtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("store-id")]
        public string storeid {
            get {
                return this.storeidField;
            }
            set {
                this.storeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associate-id")]
        public string associateid {
            get {
                return this.associateidField;
            }
            set {
                this.associateidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum ResponseMessageType {
        
        /// <remarks/>
        ACTIVATION_RESPONSE,
        
        /// <remarks/>
        ACTIVATE_NOW_RESPONSE,
        
        /// <remarks/>
        CREDIT_CHECK_RESPONSE,
        
        /// <remarks/>
        DEACTIVATION_RESPONSE,
        
        /// <remarks/>
        PARSE_RESPONSE,
        
        /// <remarks/>
        CANCELLED_RESPONSE,
        
        /// <remarks/>
        STATUS_RESPONSE,
        
        /// <remarks/>
        PORT_ELIGIBILITY_RESPONSE,
        
        /// <remarks/>
        VALIDATION_RESPONSE,
        
        /// <remarks/>
        PORT_STATUS_RESPONSE,
        
        /// <remarks/>
        NPA_NXX_RESPONSE,
        
        /// <remarks/>
        ACCOUNT_VALIDATION_RESPONSE,
        
        /// <remarks/>
        CREDIT_CANCEL_RESPONSE,
        
        /// <remarks/>
        PRE_AUTHORIZATION_RESPONSE,
        
        /// <remarks/>
        PLANS_RESPONSE,
        
        /// <remarks/>
        OPTIONS_RESPONSE,
        
        /// <remarks/>
        BILL_SUMMARY_RESPONSE,
        
        /// <remarks/>
        SERVICE_VALIDATION_RESPONSE,
        
        /// <remarks/>
        SECURITY_QUESTION_RESPONSE,
        
        /// <remarks/>
        INVENTORY_CHECK_RESPONSE,
        
        /// <remarks/>
        AUTHENTICATE_RESEND_PIN_RESPONSE,
        
        /// <remarks/>
        COVERAGE_CHECK_RESPONSE,
        
        /// <remarks/>
        CORPORATE_DISCOUNT_RESPONSE,
        
        /// <remarks/>
        ACTIVATE_RESERVED_DEVICE_RESPONSE,
        
        /// <remarks/>
        DEVICE_INFO_RESPONSE,
        
        /// <remarks/>
        ORDER_STATUS_RESPONSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nextel.com/ovm")]
    public enum ResponseMessageHeaderBrandtype {
        
        /// <remarks/>
        NX,
        
        /// <remarks/>
        SP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("ackResponse", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class ParseResponse {
        
        private ParseResponseType parseresultField;
        
        private string detailsField;
        
        private string sprintorderidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parse-result")]
        public ParseResponseType parseresult {
            get {
                return this.parseresultField;
            }
            set {
                this.parseresultField = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sprint-order-id")]
        public string sprintorderid {
            get {
                return this.sprintorderidField;
            }
            set {
                this.sprintorderidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum ParseResponseType {
        
        /// <remarks/>
        ACK,
        
        /// <remarks/>
        NACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("getBillSummary", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class BillSummaryRequest {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("account-number", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("activation-zip-code", typeof(string), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("order-type", typeof(System.Nullable<OrderType>))]
        [System.Xml.Serialization.XmlElementAttribute("plan", typeof(BillSummaryPlan), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("reference-ptn", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("second-bill", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    public enum OrderType {
        
        /// <remarks/>
        NEW,
        
        /// <remarks/>
        ADD_ON,
        
        /// <remarks/>
        UPGRADE,
        
        /// <remarks/>
        REPLACE,
        
        /// <remarks/>
        BOOST,
        
        /// <remarks/>
        FAC,
        
        /// <remarks/>
        SERVICE_ONLY,
        
        /// <remarks/>
        ADDON_PPTOFAMILY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("account-number")]
        accountnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("activation-zip-code")]
        activationzipcode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("order-type")]
        ordertype,
        
        /// <remarks/>
        plan,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("reference-ptn")]
        referenceptn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("second-bill")]
        secondbill,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("getBillSummaryResponse", Namespace="http://nextel.com/ovm", IsNullable=false)]
    public partial class BillSummaryResponse {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bill-estimate", typeof(BillEstimateData))]
        [System.Xml.Serialization.XmlElementAttribute("total-activation-fee", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("total-feature-charges", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("total-monthly-charges", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("total-price-plan-charges", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nextel.com/ovm", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("bill-estimate")]
        billestimate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("total-activation-fee")]
        totalactivationfee,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("total-feature-charges")]
        totalfeaturecharges,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("total-monthly-charges")]
        totalmonthlycharges,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("total-price-plan-charges")]
        totalpriceplancharges,
    }
}
