CREATE LOGIN [jrowles]
    WITH PASSWORD = N'lgriyd|bpSr|9mwlyvNczln_msFT7_&#$!~<8Oj$y|xubl|g', SID = 0xE2FA13D1B5C23F4CB6F84C60ECFD706E, DEFAULT_DATABASE = [CARTOYS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

