CREATE LOGIN [rdsql]
    WITH PASSWORD = N'LlFgriy d|br|gmowly#fVvcmsFT7_&#$!~<yzlenjyxub|g', SID = 0x6E98BD7CA421ED4F9BECA787EDC8BEC6, DEFAULT_DATABASE = [Scratch], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

