CREATE LOGIN [Stage1]
    WITH PASSWORD = N'hWrc:nsU,fgtOpnogoo.tthnmsFT7_&#$!~<&ufOuye,xtxo', SID = 0x9CAAD660FEB34E4CA4A858B67B4460A5, DEFAULT_DATABASE = [STAGE_CARTOYS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

