CREATE LOGIN [WebService_TMO_TEST]
    WITH PASSWORD = N'l1grsiyd|dbrO|Kmh_wlyvcHmsFT7_&#$!~<Lzl%nKjy0Ux7', SID = 0xAE5E5FF6A073C14BBC82DFC28FF57ECB, DEFAULT_DATABASE = [CARTOYS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

