CREATE LOGIN [WebService_VZW_DEV]
    WITH PASSWORD = N'hrcG$_.+nsbgtpnoooutwTthmsFT7_&#$!~<nfuyVeqOxooh', SID = 0x119AD7AD15EDE34EB2993F5984CBFA39, DEFAULT_DATABASE = [CARTOYS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

