CREATE LOGIN [WebService_TMO_DEV]
    WITH PASSWORD = N'dhArc~ns9ngtp~no,%oojtCtmsFT7_&#$!~<_hnfuyeGxohE', SID = 0x7E7ABC90518719439BD79FC0DBA6E29D, DEFAULT_DATABASE = [CARTOYS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

