CREATE LOGIN [WebService_ATT_TEST]
    WITH PASSWORD = N'lgriCyX&Fzd|bry|mZwlyv8cmsFT7_&#$!~<zPlnIjyxyub|', SID = 0x7B32C0AB6A67F04FA9F48262C154BD39, DEFAULT_DATABASE = [CARTOYS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

