//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintCSI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SprintCSI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string accountValidationResponseOption {
            get {
                return ResourceManager.GetString("accountValidationResponseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option-code.
        /// </summary>
        internal static string accountValidationResponseOptionCode {
            get {
                return ResourceManager.GetString("accountValidationResponseOptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option-price.
        /// </summary>
        internal static string accountValidationResponseOptionPrice {
            get {
                return ResourceManager.GetString("accountValidationResponseOptionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price-plan-code.
        /// </summary>
        internal static string accountValidationResponsePricePlanCode {
            get {
                return ResourceManager.GetString("accountValidationResponsePricePlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serial-number.
        /// </summary>
        internal static string accountValidationResponseSerialNumber {
            get {
                return ResourceManager.GetString("accountValidationResponseSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string activateNowSucceeded {
            get {
                return ResourceManager.GetString("activateNowSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string activateNowSuccess {
            get {
                return ResourceManager.GetString("activateNowSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account-number.
        /// </summary>
        internal static string activationAccountNumber {
            get {
                return ResourceManager.GetString("activationAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activation-fee.
        /// </summary>
        internal static string activationFee {
            get {
                return ResourceManager.GetString("activationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activation-fee-for-handset.
        /// </summary>
        internal static string activationFeeForHandset {
            get {
                return ResourceManager.GetString("activationFeeForHandset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icc-id.
        /// </summary>
        internal static string activationIccid {
            get {
                return ResourceManager.GetString("activationIccid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master-lock-code.
        /// </summary>
        internal static string activationMasterLockCode {
            get {
                return ResourceManager.GetString("activationMasterLockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meid.
        /// </summary>
        internal static string activationMeid {
            get {
                return ResourceManager.GetString("activationMeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meid-hex.
        /// </summary>
        internal static string activationMeidHex {
            get {
                return ResourceManager.GetString("activationMeidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msid.
        /// </summary>
        internal static string activationMsid {
            get {
                return ResourceManager.GetString("activationMsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one-time-lock-code.
        /// </summary>
        internal static string activationOnTimeLockCode {
            get {
                return ResourceManager.GetString("activationOnTimeLockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string activationRequestCode {
            get {
                return ResourceManager.GetString("activationRequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature.
        /// </summary>
        internal static string activationRequestFeature {
            get {
                return ResourceManager.GetString("activationRequestFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icc-id.
        /// </summary>
        internal static string activationRequestIccId {
            get {
                return ResourceManager.GetString("activationRequestIccId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meid.
        /// </summary>
        internal static string activationRequestMeid {
            get {
                return ResourceManager.GetString("activationRequestMeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service-agreement.
        /// </summary>
        internal static string activationRequestServiceAgreement {
            get {
                return ResourceManager.GetString("activationRequestServiceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result.
        /// </summary>
        internal static string activationResult {
            get {
                return ResourceManager.GetString("activationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprint-order-id.
        /// </summary>
        internal static string activationSprintOrderId {
            get {
                return ResourceManager.GetString("activationSprintOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriber-id.
        /// </summary>
        internal static string activationSubscriber {
            get {
                return ResourceManager.GetString("activationSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error-code.
        /// </summary>
        internal static string ovmErrorCode {
            get {
                return ResourceManager.GetString("ovmErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error-details.
        /// </summary>
        internal static string ovmErrorDetails {
            get {
                return ResourceManager.GetString("ovmErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ovm-error-info.
        /// </summary>
        internal static string ovmErrorInfo {
            get {
                return ResourceManager.GetString("ovmErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error-sub-name.
        /// </summary>
        internal static string ovmErrorSubName {
            get {
                return ResourceManager.GetString("ovmErrorSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error-type.
        /// </summary>
        internal static string ovmErrorType {
            get {
                return ResourceManager.GetString("ovmErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message-type.
        /// </summary>
        internal static string ovmMessageType {
            get {
                return ResourceManager.GetString("ovmMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order-id.
        /// </summary>
        internal static string ovmOrderId {
            get {
                return ResourceManager.GetString("ovmOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        internal static string parseResponseDetails {
            get {
                return ResourceManager.GetString("parseResponseDetails", resourceCulture);
            }
        }
    }
}
