ALTER TABLE [catalog].[FilterOption]
    ADD CONSTRAINT [PK_FilterOption] PRIMARY KEY CLUSTERED ([FilterOptionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

