ALTER TABLE [catalog].[RateplanService]
    ADD CONSTRAINT [PK_RateplanService] PRIMARY KEY CLUSTERED ([RateplanGuid] ASC, [ServiceGuid] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

