ALTER TABLE [catalog].[ServiceExclusion]
    ADD CONSTRAINT [PK_ServiceExclusion] PRIMARY KEY CLUSTERED ([ParentGuid] ASC, [ServiceGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

