ALTER TABLE [catalog].[GersItm]
    ADD CONSTRAINT [PK_GersItm] PRIMARY KEY CLUSTERED ([GersSku] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

