ALTER TABLE [catalog].[PropertyMasterGroup]
    ADD CONSTRAINT [PK_PropertyMasterGroup] PRIMARY KEY CLUSTERED ([PropertyMasterGroupGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

