ALTER TABLE [catalog].[GersStock]
    ADD CONSTRAINT [PK_GersStock] PRIMARY KEY CLUSTERED ([OutletId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

