ALTER TABLE [catalog].[FilterGroup]
    ADD CONSTRAINT [PK_FilterGroup] PRIMARY KEY CLUSTERED ([FilterGroupId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

