ALTER TABLE [catalog].[RateplanMarket]
    ADD CONSTRAINT [PK_RateplanMarket] PRIMARY KEY CLUSTERED ([RateplanGuid] ASC, [MarketGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

