ALTER TABLE [catalog].[DeviceService]
    ADD CONSTRAINT [PK_DeviceService] PRIMARY KEY CLUSTERED ([DeviceGuid] ASC, [ServiceGuid] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

