ALTER TABLE [catalog].[ServiceMasterGroup]
    ADD CONSTRAINT [PK_ServiceMasterGroup] PRIMARY KEY CLUSTERED ([ServiceMasterGroupGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

