ALTER TABLE [catalog].[RateplanDevice]
    ADD CONSTRAINT [PK_RateplanDevice] PRIMARY KEY CLUSTERED ([RateplanGuid] ASC, [DeviceGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

