ALTER TABLE [cart].[Recommendation]
    ADD CONSTRAINT [PK__Recommen__AA15BEE4392D3049] PRIMARY KEY CLUSTERED ([RecommendationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

