CREATE TABLE [admin].[callNoteSubjects] (
    [subjectId] INT            IDENTITY (1, 1) NOT NULL,
    [subject]   NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([subjectId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

