IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NT AUTHORITY\IUSR')
CREATE LOGIN [NT AUTHORITY\IUSR] FROM WINDOWS
GO
CREATE USER [NT AUTHORITY\IUSR] FOR LOGIN [NT AUTHORITY\IUSR]
GO
