CREATE NONCLUSTERED INDEX [IX_ProductGuid_Active_ProductId_GersSku]
    ON [catalog].[Product]([ProductGuid] ASC, [Active] ASC, [ProductId] ASC, [GersSku] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

