CREATE NONCLUSTERED INDEX [IDX_Property]
    ON [catalog].[Property]([Name] ASC, [ProductGuid] ASC, [PropertyGuid] ASC)
    INCLUDE([IsCustom], [Value], [Active]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

