CREATE TABLE [test].[WirelessLineFixIMEIOnDupShipments] (
    [WirelessLineId]          INT           NOT NULL,
    [OrderDetailId]           INT           NOT NULL,
    [PlanId]                  INT           NULL,
    [CarrierPlanId]           NVARCHAR (10) NULL,
    [PlanType]                NVARCHAR (10) NULL,
    [NewMDN]                  NCHAR (10)    NULL,
    [ESN]                     NVARCHAR (50) NULL,
    [IMEI]                    NVARCHAR (50) NULL,
    [CurrentMDN]              NVARCHAR (10) NULL,
    [CurrentCarrier]          INT           NULL,
    [IsMDNPort]               BIT           NULL,
    [PortRequestId]           NVARCHAR (10) NULL,
    [PortResponse]            NVARCHAR (10) NULL,
    [PortStatus]              NVARCHAR (10) NULL,
    [IsNPArequested]          BIT           NULL,
    [UpgradeEligible]         BIT           NULL,
    [RequestedActivationDate] DATETIME      NULL,
    [CarrierReferenceId1]     NVARCHAR (50) NULL,
    [CarrierReferenceId2]     NVARCHAR (50) NULL,
    [CarrierReferenceId3]     NVARCHAR (50) NULL,
    [PortInDueDate]           DATETIME      NULL,
    [ContractLength]          INT           NULL,
    [MonthlyFee]              MONEY         NULL,
    [MarketCode]              NVARCHAR (30) NULL,
    [NPARequested]            VARCHAR (3)   NULL,
    [SIM]                     NVARCHAR (50) NULL,
    [ActivationStatus]        INT           NULL,
    [ActivationFee]           MONEY         NULL
);

