ALTER TABLE [salesorder].[PaymentMethod]
    ADD CONSTRAINT [PK__PaymentMethods__5090EFD7] PRIMARY KEY CLUSTERED ([PaymentMethodId] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

