ALTER TABLE [salesorder].[WirelessAccount]
    ADD CONSTRAINT [PK_WirelessAccount] PRIMARY KEY CLUSTERED ([WirelessAccountId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

