ALTER TABLE [salesorder].[Address]
    ADD CONSTRAINT [IX_Address] UNIQUE NONCLUSTERED ([AddressGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

