ALTER TABLE [ups].[ZoneCodes980]
    ADD CONSTRAINT [PK_ZoneCodes980] PRIMARY KEY CLUSTERED ([ZipStart] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

