CREATE TABLE [dbo].[Load_Plans]
(
[plan_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_network] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[service_agreement] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_tier] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_price] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[affiliate_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cell_rounding] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_effective_date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_expiration_date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_on_plan_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[long_distance_overage] [bit] NULL,
[national_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wireless_data_services] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[night_and_weekend_minutes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_promo_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_regional_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_store_front_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cell_minutes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdma_roaming] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cell_overage_charge] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[voice_mail_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[caller_id_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_connect_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[long_distance_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ready_link_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ready_link_group_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobile_to_mobile_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nationwide_direct_connect_yn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nationwide_dc_overage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[share] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_desc] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[direct_connect_minutes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[direct_connect_overage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_connect_overage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[terms_and_conditions] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAN_Id2] [numeric] (20, 0) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
