ALTER TABLE [account].[RoleMenu]
    ADD CONSTRAINT [PK_RoleMenu] PRIMARY KEY CLUSTERED ([RoleGuid] ASC, [MenuGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

