ALTER TABLE [account].[RoleFunctionality]
    ADD CONSTRAINT [PK_RoleFunctionality] PRIMARY KEY CLUSTERED ([RoleGuid] ASC, [FunctionalityGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

