ALTER TABLE [account].[Functionality]
    ADD CONSTRAINT [PK_Functionality] PRIMARY KEY CLUSTERED ([FunctionalityGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

