//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMenu
    {
        public System.Guid AdminMenuId { get; set; }
        public string Label { get; set; }
        public string DisplayFile { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Ordinal { get; set; }
    }
}
