//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogload_rateplan
    {
        public string Type { get; set; }
        public string Object { get; set; }
        public string RateplanCode { get; set; }
        public bool Active { get; set; }
        public string ModifiedValue { get; set; }
        public string PreviousType { get; set; }
        public string NewType { get; set; }
        public string PreviousMaxLines { get; set; }
        public string NewMaxLines { get; set; }
        public string PreviousMonthlyFee { get; set; }
        public string NewMonthlyFee { get; set; }
        public string PreviousAdditionalLineFee { get; set; }
        public string NewAdditionalLineFee { get; set; }
        public string PreviousPrimaryActivationFee { get; set; }
        public string NewPrimaryActivationFee { get; set; }
        public string PreviousSecondaryActivationFee { get; set; }
        public string NewSecondaryActivationFee { get; set; }
        public string PreviousContractTerm { get; set; }
        public string NewContractTerm { get; set; }
        public string PreviousIncludedLines { get; set; }
        public string NewIncludedLines { get; set; }
        public string PreviousIsShared { get; set; }
        public string NewIsShared { get; set; }
        public string PreviousName { get; set; }
        public string NewName { get; set; }
        public string PK { get; set; }
    }
}
