//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentInventory
    {
        public string GersSku { get; set; }
        public Nullable<int> TotalStock { get; set; }
        public Nullable<int> TotalRealStock { get; set; }
        public Nullable<int> TotalRealStockOrders { get; set; }
        public Nullable<int> TotalVirtualStock { get; set; }
        public Nullable<int> TotalVirtualOrders { get; set; }
    }
}
