//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServiceActivation
    {
        public string OrderDate { get; set; }
        public string PcrDate { get; set; }
        public string twodaydate { get; set; }
        public Nullable<int> DaysFromSLA { get; set; }
        public int OrderId { get; set; }
        public string Carrier { get; set; }
        public string ActivationType { get; set; }
        public string Status { get; set; }
        public string ActivationDate { get; set; }
        public string LastActivationNote { get; set; }
        public string TrackingNumber { get; set; }
        public string ShipmentDeliveryDate { get; set; }
        public string ShipMethod { get; set; }
        public string ActivationStatus { get; set; }
        public Nullable<int> DeviceTotal { get; set; }
        public Nullable<int> PushActivationTotal { get; set; }
        public Nullable<int> ManualActivationTotal { get; set; }
        public Nullable<int> PendingActivationTotal { get; set; }
        public Nullable<int> PendingCapture { get; set; }
        public string CapturedBy { get; set; }
        public string ActivatedBy { get; set; }
    }
}
