//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataGroup
    {
        public DataGroup()
        {
            this.Data = new HashSet<Datum>();
        }
    
        public long DataGroupID { get; set; }
        public long TemplateID { get; set; }
        public string SelectSQL { get; set; }
    
        public virtual ICollection<Datum> Data { get; set; }
        public virtual Template Template { get; set; }
    }
}
