//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image1
    {
        public Image1()
        {
            this.CarrierImages = new HashSet<CarrierImage>();
        }
    
        public long ImageID { get; set; }
        public System.Guid ImageGUID { get; set; }
        public bool Active { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> TypeID { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ApprovedRequestedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public byte[] BinaryContent { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string AltTag { get; set; }
        public string LinkURL { get; set; }
        public string Rel { get; set; }
    
        public virtual ICollection<CarrierImage> CarrierImages { get; set; }
        public virtual Category1 Category { get; set; }
        public virtual Content Content { get; set; }
        public virtual Type Type { get; set; }
    }
}
