//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public System.Guid MarketGuid { get; set; }
        public System.Guid CarrierGuid { get; set; }
        public string CarrierMarketCode { get; set; }
        public string CarrierMarketName { get; set; }
    }
}
