//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryBase
    {
        public int BaseId { get; set; }
        public int BranchId { get; set; }
        public string BaseName { get; set; }
        public bool Kiosk { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string MainNumber { get; set; }
        public string StoreHours { get; set; }
        public Nullable<int> KioskCode { get; set; }
        public string StoreCode { get; set; }
    
        public virtual MilitaryBranch MilitaryBranch { get; set; }
    }
}
