//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyMasterGroup
    {
        public PropertyMasterGroup()
        {
            this.PropertyMasters = new HashSet<PropertyMaster>();
        }
    
        public System.Guid PropertyMasterGroupGuid { get; set; }
        public string ProductType { get; set; }
        public string PropertyType { get; set; }
        public string Label { get; set; }
        public Nullable<int> Ordinal { get; set; }
    
        public virtual ICollection<PropertyMaster> PropertyMasters { get; set; }
    }
}
