//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebateToFilter
    {
        public System.Guid RebateToFilterGuid { get; set; }
        public System.Guid RebateGuid { get; set; }
        public int FilterOptionId { get; set; }
        public Nullable<int> FilterGroupId { get; set; }
    }
}
