//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseState
    {
        public long ReleaseID { get; set; }
        public string ControlName { get; set; }
        public bool ControlState { get; set; }
        public string Value { get; set; }
        public Nullable<long> ReleaseTaskID { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
