//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release1
    {
        public long ReleaseID { get; set; }
        public bool Completed { get; set; }
        public string ChannelName { get; set; }
        public string ReleaseName { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.Guid ReleaseManager { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long CurrentInstance { get; set; }
        public long NewInstance { get; set; }
    }
}
