//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedStock
    {
        public string SessionId { get; set; }
        public int GroupNumber { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
        public System.DateTime ReservedTime { get; set; }
    }
}
