//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDataFeature
    {
        public int ServiceDataFeatureId { get; set; }
        public System.Guid ServiceGuid { get; set; }
        public System.Guid ServiceDataGroupGuid { get; set; }
        public string DeviceType { get; set; }
    }
}
