//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public Nullable<int> ShipMethodId { get; set; }
        public string TrackingNumber { get; set; }
        public string DeliveryStatus { get; set; }
    
        public virtual ShipMethod ShipMethod { get; set; }
    }
}
