//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipMethod
    {
        public ShipMethod()
        {
            this.Shipments = new HashSet<Shipment>();
        }
    
        public int ShipMethodId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> DefaultFixedCost { get; set; }
        public int GersShipMethodId { get; set; }
        public string CarrierId { get; set; }
        public Nullable<decimal> PromoPrice { get; set; }
        public string PromoDisplayName { get; set; }
        public string PromoCarrierId { get; set; }
        public Nullable<bool> IsApoAfoAvailable { get; set; }
    
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
