//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteGroup
    {
        public SiteGroup()
        {
            this.Data = new HashSet<Datum>();
            this.Locations = new HashSet<Location>();
            this.Releases = new HashSet<Release>();
            this.Sites = new HashSet<Site>();
        }
    
        public long SiteGroupID { get; set; }
        public string Name { get; set; }
        public bool Locked { get; set; }
    
        public virtual ICollection<Datum> Data { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Release> Releases { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
