//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Releases = new HashSet<Release>();
            this.SiteTemplates = new HashSet<SiteTemplate>();
        }
    
        public long SiteID { get; set; }
        public System.Guid SiteGUID { get; set; }
        public long SiteGroupID { get; set; }
        public long EnvironmentID { get; set; }
        public string URLIdentifier { get; set; }
        public string StaticImageURL { get; set; }
        public string SiteURL { get; set; }
        public bool Locked { get; set; }
        public bool DisableCache { get; set; }
    
        public virtual ICollection<Release> Releases { get; set; }
        public virtual SiteGroup SiteGroup { get; set; }
        public virtual ICollection<SiteTemplate> SiteTemplates { get; set; }
    }
}
