//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public long TagID { get; set; }
        public long TemplateID { get; set; }
        public string TagKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TagType { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
