//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public string PosterFileName { get; set; }
        public bool Active { get; set; }
        public int Ordinal { get; set; }
    }
}
