//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPaymentDiff
    {
        public int OrderId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> GERSStatus { get; set; }
        public Nullable<decimal> ShipCost { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> PaymentDiffs { get; set; }
    }
}
