//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostcoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class warranty
    {
        public System.Guid WarrantyGuid { get; set; }
        public string CarrierId { get; set; }
        public string UPC { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> ContractTerm { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Deductible { get; set; }
        public Nullable<decimal> MonthlyFee { get; set; }
        public Nullable<decimal> AdditionalDevicePrice { get; set; }
        public Nullable<decimal> AdditionalDeviceDeductible { get; set; }
        public Nullable<decimal> AdditionalDeviceMonthlyFee { get; set; }
    }
}
