ALTER TABLE [admin].[callNotes]
    ADD CONSTRAINT [PK__callNote__03C97EFD17CC3C7E] PRIMARY KEY CLUSTERED ([noteId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

