//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintCarrierServiceTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SprintCarrierServiceTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string accountValidationResponseOption {
            get {
                return ResourceManager.GetString("accountValidationResponseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option-code.
        /// </summary>
        internal static string accountValidationResponseOptionCode {
            get {
                return ResourceManager.GetString("accountValidationResponseOptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option-price.
        /// </summary>
        internal static string accountValidationResponseOptionPrice {
            get {
                return ResourceManager.GetString("accountValidationResponseOptionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature.
        /// </summary>
        internal static string activationRequestFeature {
            get {
                return ResourceManager.GetString("activationRequestFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order.
        /// </summary>
        internal static string activationRequestOrder {
            get {
                return ResourceManager.GetString("activationRequestOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string activationRequestOrderType {
            get {
                return ResourceManager.GetString("activationRequestOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error-code.
        /// </summary>
        internal static string errorCode {
            get {
                return ResourceManager.GetString("errorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ovm-error-info.
        /// </summary>
        internal static string errorInfo {
            get {
                return ResourceManager.GetString("errorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meid.
        /// </summary>
        internal static string meid {
            get {
                return ResourceManager.GetString("meid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ovm xmlns=&quot;http://nextel.com/ovm&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://tdas4208.test.sprint.com:4653/ovm/&quot;&gt;&lt;ovm-header&gt;&lt;message-type&gt;ACCOUNT_VALIDATION_RESPONSE&lt;/message-type&gt;&lt;timestamp&gt;2014-02-18T00:00:00&lt;/timestamp&gt;&lt;resend-number&gt;1&lt;/resend-number&gt;&lt;/ovm-header&gt;&lt;ovm-response&gt;&lt;account-validation-response&gt;&lt;account-status&gt;ACTIVE&lt;/account-status&gt;&lt;account-number&gt;807708248&lt;/account-number&gt;&lt;number-handsets-approved&gt;9&lt;/number-handsets-approved&gt;&lt;account-info&gt;&lt;current-subs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLHelperFacts_AcccountValidationResponseForError {
            get {
                return ResourceManager.GetString("XMLHelperFacts_AcccountValidationResponseForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ovm xmlns=&quot;http://nextel.com/ovm&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///     xsi:schemaLocation=&quot;http://tdas4219.test.sprint.com:4613/ovm/&quot;&gt;
        ///    &lt;ovm-header&gt;
        ///        &lt;message-type&gt;ACCOUNT_VALIDATION_RESPONSE&lt;/message-type&gt;
        ///        &lt;timestamp&gt;2014-02-07T00:00:00&lt;/timestamp&gt;
        ///        &lt;resend-number&gt;1&lt;/resend-number&gt;
        ///    &lt;/ovm-header&gt;
        ///    &lt;ovm-response&gt;
        ///        &lt;account-validation-response&gt;
        ///            &lt;account-status&gt;ACTIVE&lt;/account-status&gt;
        ///            &lt;account-number&gt;998592149&lt;/acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLHelperFacts_accountValidationResponse {
            get {
                return ResourceManager.GetString("XMLHelperFacts_accountValidationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SprintActivateReservedDeviceResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;ErrorCode&gt;1&lt;/ErrorCode&gt;
        ///    &lt;ServiceResponseSubCode&gt;1010&lt;/ServiceResponseSubCode&gt;
        ///    &lt;CallerLineNumber&gt;0&lt;/CallerLineNumber&gt;
        ///    &lt;ErrorCodeEnum&gt;Success&lt;/ErrorCodeEnum&gt;
        ///    &lt;ServiceResponseSubCodeEnum&gt;DefaultValue&lt;/ServiceResponseSubCodeEnum&gt;
        ///    &lt;SprintErrorCode&gt;0&lt;/SprintErrorCode&gt;
        ///    &lt;SprintErrorCodeEnum&gt;DefaultValue&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLHelperFacts_ActivateReservedDeviceResponse {
            get {
                return ResourceManager.GetString("XMLHelperFacts_ActivateReservedDeviceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ovm xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///     xmlns=&quot;http://nextel.com/ovm&quot;&gt;
        ///    &lt;ovm-header&gt;
        ///        &lt;pin&gt;6654&lt;/pin&gt;
        ///        &lt;vendor-code&gt;CO&lt;/vendor-code&gt;
        ///        &lt;order-id&gt;13822044340409801435659&lt;/order-id&gt;
        ///        &lt;message-type&gt;ACTIVATION_REQUEST&lt;/message-type&gt;
        ///        &lt;timestamp&gt;2014-02-07T15:42:35.799349-08:00&lt;/timestamp&gt;
        ///        &lt;brand-type&gt;SP&lt;/brand-type&gt;
        ///    &lt;/ovm-header&gt;
        ///    &lt;ovm-request [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlHelperFacts_activationRequestUPGRADE {
            get {
                return ResourceManager.GetString("XmlHelperFacts_activationRequestUPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ovm xmlns=&quot;http://nextel.com/ovm&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://nextel.com/ovm http://tdas4219.test.sprint.com:4613/ovm/xsd/ovm-response.xsd&quot;&gt;
        ///    &lt;ovm-header&gt;
        ///        &lt;vendor-code&gt;CO&lt;/vendor-code&gt;
        ///        &lt;order-id&gt;1382204434040131968&lt;/order-id&gt;
        ///        &lt;message-type&gt;ACTIVATION_RESPONSE&lt;/message-type&gt;
        ///        &lt;timestamp&gt;2013-12-22T23:09:39-06:00&lt;/timestamp&gt;
        ///        &lt;resend-number&gt;0&lt;/resend-number&gt;
        ///        &lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLHelperFacts_activationResponseActiveOrFraudulent {
            get {
                return ResourceManager.GetString("XMLHelperFacts_activationResponseActiveOrFraudulent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ovm xmlns=&quot;http://nextel.com/ovm&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://nextel.com/ovm http://tdas4219.test.sprint.com:4613/ovm/xsd/ovm-response.xsd&quot;&gt;
        ///    &lt;ovm-header&gt;
        ///        &lt;vendor-code&gt;CO&lt;/vendor-code&gt;
        ///        &lt;order-id&gt;1382204434040498355&lt;/order-id&gt;
        ///        &lt;message-type&gt;CREDIT_CHECK_RESPONSE&lt;/message-type&gt;
        ///        &lt;timestamp&gt;2013-12-30T18:53:56-06:00&lt;/timestamp&gt;
        ///        &lt;resend-number&gt;0&lt;/resend-number&gt;
        ///    &lt;/ovm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLHelperFacts_creditCheckResponse {
            get {
                return ResourceManager.GetString("XMLHelperFacts_creditCheckResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeserializeXML Failed There is an error in XML document (1, 1231). ==&gt;.
        /// </summary>
        internal static string XmlHelperFacts_DeserializeXmlFailedMessage {
            get {
                return ResourceManager.GetString("XmlHelperFacts_DeserializeXmlFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ovm xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://nextel.com/ovm&quot;&gt;
        ///  &lt;ovm-header&gt;
        ///    &lt;pin&gt;6654&lt;/pin&gt;
        ///    &lt;vendor-code&gt;CO&lt;/vendor-code&gt;
        ///    &lt;order-id /&gt;
        ///    &lt;message-type&gt;ACTIVATION_REQUEST&lt;/message-type&gt;
        ///    &lt;timestamp&gt;2014-02-07T15:42:35.799349-08:00&lt;/timestamp&gt;
        ///    &lt;brand-type&gt;SP&lt;/brand-type&gt;
        ///  &lt;/ovm-header&gt;
        ///  &lt;ovm-request&gt;
        ///    &lt;activation-request&gt;
        ///      &lt;order type=&quot;REPLACE&quot; /&gt;
        ///      &lt;order-date&gt;2014-02-05T00:00:00&lt;/order-da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlHelperFacts_ExpectedActivationReplaceRequestForOneLine {
            get {
                return ResourceManager.GetString("XmlHelperFacts_ExpectedActivationReplaceRequestForOneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ovm xmlns=&quot;http://nextel.com/ovm&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///     xsi:schemaLocation=&quot;http://tdas4219.test.sprint.com:4613/ovm/&quot;&gt;
        ///    &lt;ovm-header&gt;
        ///        &lt;message-type&gt;ACCOUNT_VALIDATION_RESPONSE&lt;/message-type&gt;
        ///        &lt;timestamp&gt;2014-02-10T00:00:00&lt;/timestamp&gt;
        ///        &lt;resend-number&gt;1&lt;/resend-number&gt;
        ///    &lt;/ovm-header&gt;
        ///    &lt;ovm-response&gt;
        ///        &lt;account-validation-response&gt;
        ///            &lt;account-status&gt;ACTIVE&lt;/account-status&gt;
        ///            &lt;account-number&gt;529492145&lt;/acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlHelperFacts_MultiSubscriber_accountValidationResponse {
            get {
                return ResourceManager.GetString("XmlHelperFacts_MultiSubscriber_accountValidationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Fault xmlns=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;faultcode xmlns=&quot;&quot;&gt;Client.705&lt;/faultcode&gt;
        ///  &lt;faultstring xmlns=&quot;&quot;&gt;Input validation error&lt;/faultstring&gt;
        ///  &lt;faultactor xmlns=&quot;&quot;&gt;76S&lt;/faultactor&gt;
        ///  &lt;detail xmlns=&quot;&quot;&gt;
        ///    &lt;ns1:errorDetailItem xmlns:ns1=&quot;http://integration.sprint.com/common/ErrorDetailsV2.xsd&quot;&gt;
        ///      &lt;ns1:providerError&gt;
        ///        &lt;ns1:providerErrorCode&gt;Client.705&lt;/ns1:providerErrorCode&gt;
        ///        &lt;ns1:providerErrorText&gt;http://208.10.68.88:10004/services/QueryPlansAndOptionsService: cvc-par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlHelperFacts_SoapFault {
            get {
                return ResourceManager.GetString("XmlHelperFacts_SoapFault", resourceCulture);
            }
        }
    }
}
