ALTER TABLE [dbo].[Users]
    ADD CONSTRAINT [PK_users_temp_2] PRIMARY KEY CLUSTERED ([User_ID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

