ALTER TABLE [dbo].[AdminMenu]
    ADD CONSTRAINT [PK_AdminMenu] PRIMARY KEY CLUSTERED ([AdminMenuId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

