ALTER TABLE [dbo].[AdminComponent]
    ADD CONSTRAINT [PK_AdminComponent] PRIMARY KEY CLUSTERED ([AdminComponentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

