ALTER TABLE [dbo].[Coupon]
    ADD CONSTRAINT [PK_Coupon] PRIMARY KEY CLUSTERED ([CouponId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

