ALTER TABLE [service].[CustomerLookUpPlan]
    ADD CONSTRAINT [PK__Customer__8204AE0D04053AF3] PRIMARY KEY CLUSTERED ([CustomerLookUpPlanId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

