ALTER TABLE [service].[PaymentGatewayListener]
    ADD CONSTRAINT [PK_PaymentGatewayListener] PRIMARY KEY CLUSTERED ([AsyncId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

