ALTER TABLE [service].[CheckoutSessionState]
    ADD CONSTRAINT [PK_CheckoutSessionState] PRIMARY KEY CLUSTERED ([CheckoutSessionStateGUID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

