//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMobileCarrierServiceInterface.Interfaces.CustomerDocument {
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
    using TMobileCarrierServiceInterface.Interfaces.Common;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CustomerDocumentServiceSOAPBinding", Namespace="http://retail.tmobile.com/service")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StoreInfo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StoreKey))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RspRequest))]
public partial class CustomerDocumentService : Microsoft.Web.Services2.WebServicesClientProtocol {
    
    private System.Threading.SendOrPostCallback createServiceAgreementOperationCompleted;
    
    private System.Threading.SendOrPostCallback saveDocumentOperationCompleted;
    
    private System.Threading.SendOrPostCallback createEIPDisclosureDocumentOperationCompleted;
    
    private System.Threading.SendOrPostCallback createEasyPayTermsAndConditionsOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCustomerServiceGuideOperationCompleted;
    
    /// <remarks/>
    public CustomerDocumentService() {
        this.Url = "http://localhost:7001/eProxy/service/CustomerDocumentService_SOAP_V1";
    }
    
    /// <remarks/>
    public event createServiceAgreementCompletedEventHandler createServiceAgreementCompleted;
    
    /// <remarks/>
    public event saveDocumentCompletedEventHandler saveDocumentCompleted;
    
    /// <remarks/>
    public event createEIPDisclosureDocumentCompletedEventHandler createEIPDisclosureDocumentCompleted;
    
    /// <remarks/>
    public event createEasyPayTermsAndConditionsCompletedEventHandler createEasyPayTermsAndConditionsCompleted;
    
    /// <remarks/>
    public event getCustomerServiceGuideCompletedEventHandler getCustomerServiceGuideCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("createServiceAgreement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("customerDocumentResponse", Namespace="http://retail.tmobile.com/sdo")]
    public CustomerDocumentResponse createServiceAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://retail.tmobile.com/sdo")] CreateServiceAgreementRequest createServiceAgreementRequest) {
        object[] results = this.Invoke("createServiceAgreement", new object[] {
                    createServiceAgreementRequest});
        return ((CustomerDocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateServiceAgreement(CreateServiceAgreementRequest createServiceAgreementRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createServiceAgreement", new object[] {
                    createServiceAgreementRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public CustomerDocumentResponse EndcreateServiceAgreement(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CustomerDocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public void createServiceAgreementAsync(CreateServiceAgreementRequest createServiceAgreementRequest) {
        this.createServiceAgreementAsync(createServiceAgreementRequest, null);
    }
    
    /// <remarks/>
    public void createServiceAgreementAsync(CreateServiceAgreementRequest createServiceAgreementRequest, object userState) {
        if ((this.createServiceAgreementOperationCompleted == null)) {
            this.createServiceAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateServiceAgreementOperationCompleted);
        }
        this.InvokeAsync("createServiceAgreement", new object[] {
                    createServiceAgreementRequest}, this.createServiceAgreementOperationCompleted, userState);
    }
    
    private void OncreateServiceAgreementOperationCompleted(object arg) {
        if ((this.createServiceAgreementCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createServiceAgreementCompleted(this, new createServiceAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("saveDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("saveDocumentResponse", Namespace="http://retail.tmobile.com/sdo")]
    public SaveDocumentResponse saveDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://retail.tmobile.com/sdo")] SaveDocumentRequest saveDocumentRequest) {
        object[] results = this.Invoke("saveDocument", new object[] {
                    saveDocumentRequest});
        return ((SaveDocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsaveDocument(SaveDocumentRequest saveDocumentRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("saveDocument", new object[] {
                    saveDocumentRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public SaveDocumentResponse EndsaveDocument(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SaveDocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public void saveDocumentAsync(SaveDocumentRequest saveDocumentRequest) {
        this.saveDocumentAsync(saveDocumentRequest, null);
    }
    
    /// <remarks/>
    public void saveDocumentAsync(SaveDocumentRequest saveDocumentRequest, object userState) {
        if ((this.saveDocumentOperationCompleted == null)) {
            this.saveDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveDocumentOperationCompleted);
        }
        this.InvokeAsync("saveDocument", new object[] {
                    saveDocumentRequest}, this.saveDocumentOperationCompleted, userState);
    }
    
    private void OnsaveDocumentOperationCompleted(object arg) {
        if ((this.saveDocumentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveDocumentCompleted(this, new saveDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("createEIPDisclosureDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("documentResponse", Namespace="http://retail.tmobile.com/sdo")]
    public DocumentResponse createEIPDisclosureDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://retail.tmobile.com/sdo")] CreateEIPDisclosureDocumentRequest createEIPDisclosureDocumentRequest) {
        object[] results = this.Invoke("createEIPDisclosureDocument", new object[] {
                    createEIPDisclosureDocumentRequest});
        return ((DocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateEIPDisclosureDocument(CreateEIPDisclosureDocumentRequest createEIPDisclosureDocumentRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createEIPDisclosureDocument", new object[] {
                    createEIPDisclosureDocumentRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public DocumentResponse EndcreateEIPDisclosureDocument(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public void createEIPDisclosureDocumentAsync(CreateEIPDisclosureDocumentRequest createEIPDisclosureDocumentRequest) {
        this.createEIPDisclosureDocumentAsync(createEIPDisclosureDocumentRequest, null);
    }
    
    /// <remarks/>
    public void createEIPDisclosureDocumentAsync(CreateEIPDisclosureDocumentRequest createEIPDisclosureDocumentRequest, object userState) {
        if ((this.createEIPDisclosureDocumentOperationCompleted == null)) {
            this.createEIPDisclosureDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateEIPDisclosureDocumentOperationCompleted);
        }
        this.InvokeAsync("createEIPDisclosureDocument", new object[] {
                    createEIPDisclosureDocumentRequest}, this.createEIPDisclosureDocumentOperationCompleted, userState);
    }
    
    private void OncreateEIPDisclosureDocumentOperationCompleted(object arg) {
        if ((this.createEIPDisclosureDocumentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createEIPDisclosureDocumentCompleted(this, new createEIPDisclosureDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("createEasyPayTermsAndConditions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("documentResponse", Namespace="http://retail.tmobile.com/sdo")]
    public DocumentResponse createEasyPayTermsAndConditions([System.Xml.Serialization.XmlElementAttribute(Namespace="http://retail.tmobile.com/sdo")] CreateEasyPayTermsAndConditionsRequest createEasyPayTermsAndConditionsRequest) {
        object[] results = this.Invoke("createEasyPayTermsAndConditions", new object[] {
                    createEasyPayTermsAndConditionsRequest});
        return ((DocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateEasyPayTermsAndConditions(CreateEasyPayTermsAndConditionsRequest createEasyPayTermsAndConditionsRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createEasyPayTermsAndConditions", new object[] {
                    createEasyPayTermsAndConditionsRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public DocumentResponse EndcreateEasyPayTermsAndConditions(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DocumentResponse)(results[0]));
    }
    
    /// <remarks/>
    public void createEasyPayTermsAndConditionsAsync(CreateEasyPayTermsAndConditionsRequest createEasyPayTermsAndConditionsRequest) {
        this.createEasyPayTermsAndConditionsAsync(createEasyPayTermsAndConditionsRequest, null);
    }
    
    /// <remarks/>
    public void createEasyPayTermsAndConditionsAsync(CreateEasyPayTermsAndConditionsRequest createEasyPayTermsAndConditionsRequest, object userState) {
        if ((this.createEasyPayTermsAndConditionsOperationCompleted == null)) {
            this.createEasyPayTermsAndConditionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateEasyPayTermsAndConditionsOperationCompleted);
        }
        this.InvokeAsync("createEasyPayTermsAndConditions", new object[] {
                    createEasyPayTermsAndConditionsRequest}, this.createEasyPayTermsAndConditionsOperationCompleted, userState);
    }
    
    private void OncreateEasyPayTermsAndConditionsOperationCompleted(object arg) {
        if ((this.createEasyPayTermsAndConditionsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createEasyPayTermsAndConditionsCompleted(this, new createEasyPayTermsAndConditionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getCustomerServiceGuide", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("customerServiceGuideResponse", Namespace="http://retail.tmobile.com/sdo")]
    public CustomerServiceGuideResponse getCustomerServiceGuide([System.Xml.Serialization.XmlElementAttribute(Namespace="http://retail.tmobile.com/sdo")] CustomerServiceGuideRequest customerServiceGuideRequest) {
        object[] results = this.Invoke("getCustomerServiceGuide", new object[] {
                    customerServiceGuideRequest});
        return ((CustomerServiceGuideResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCustomerServiceGuide(CustomerServiceGuideRequest customerServiceGuideRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCustomerServiceGuide", new object[] {
                    customerServiceGuideRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public CustomerServiceGuideResponse EndgetCustomerServiceGuide(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CustomerServiceGuideResponse)(results[0]));
    }
    
    /// <remarks/>
    public void getCustomerServiceGuideAsync(CustomerServiceGuideRequest customerServiceGuideRequest) {
        this.getCustomerServiceGuideAsync(customerServiceGuideRequest, null);
    }
    
    /// <remarks/>
    public void getCustomerServiceGuideAsync(CustomerServiceGuideRequest customerServiceGuideRequest, object userState) {
        if ((this.getCustomerServiceGuideOperationCompleted == null)) {
            this.getCustomerServiceGuideOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerServiceGuideOperationCompleted);
        }
        this.InvokeAsync("getCustomerServiceGuide", new object[] {
                    customerServiceGuideRequest}, this.getCustomerServiceGuideOperationCompleted, userState);
    }
    
    private void OngetCustomerServiceGuideOperationCompleted(object arg) {
        if ((this.getCustomerServiceGuideCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCustomerServiceGuideCompleted(this, new getCustomerServiceGuideCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CreateServiceAgreementRequest : RspRequest {
    
    private string representativeField;
    
    private string storeNameField;
    
    private string storePhoneField;
    
    private string billingAccountNumberField;
    
    private string[] subscriberNumbersField;
    
    private LanguageEnum agreementLanguageField;
    
    private ServiceAgreementActivityCodeEnum serviceAgreementActivityCodeField;
    
    private decimal orderFeeField;
    
    private bool orderFeeFieldSpecified;
    
    public CreateServiceAgreementRequest() {
        this.agreementLanguageField = LanguageEnum.ENGLISH;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string representative {
        get {
            return this.representativeField;
        }
        set {
            this.representativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string storeName {
        get {
            return this.storeNameField;
        }
        set {
            this.storeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string storePhone {
        get {
            return this.storePhoneField;
        }
        set {
            this.storePhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string billingAccountNumber {
        get {
            return this.billingAccountNumberField;
        }
        set {
            this.billingAccountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("subscriberNumbers", DataType="token")]
    public string[] subscriberNumbers {
        get {
            return this.subscriberNumbersField;
        }
        set {
            this.subscriberNumbersField = value;
        }
    }
    
    /// <remarks/>
    public LanguageEnum agreementLanguage {
        get {
            return this.agreementLanguageField;
        }
        set {
            this.agreementLanguageField = value;
        }
    }
    
    /// <remarks/>
    public ServiceAgreementActivityCodeEnum serviceAgreementActivityCode {
        get {
            return this.serviceAgreementActivityCodeField;
        }
        set {
            this.serviceAgreementActivityCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal orderFee {
        get {
            return this.orderFeeField;
        }
        set {
            this.orderFeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderFeeSpecified {
        get {
            return this.orderFeeFieldSpecified;
        }
        set {
            this.orderFeeFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class ItemDetailParams {
    
    private string skuField;
    
    private string descriptorField;
    
    private string serialNumField;
    
    private string epinNumField;
    
    private decimal quantityField;
    
    private decimal sellingPriceField;
    
    private decimal eipDownPaymentField;
    
    private bool eipDownPaymentFieldSpecified;
    
    private ContractLengthEnum contractTermField;
    
    private bool contractTermFieldSpecified;
    
    private bool voidedField;
    
    private int activationReasonIdField;
    
    private bool activationReasonIdFieldSpecified;
    
    private int overrideReasonIdField;
    
    private bool overrideReasonIdFieldSpecified;
    
    private int returnReasonIdField;
    
    private bool returnReasonIdFieldSpecified;
    
    private string flexCardNumberField;
    
    private string flexCardControlNumberField;
    
    public ItemDetailParams() {
        this.voidedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sku {
        get {
            return this.skuField;
        }
        set {
            this.skuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string descriptor {
        get {
            return this.descriptorField;
        }
        set {
            this.descriptorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string serialNum {
        get {
            return this.serialNumField;
        }
        set {
            this.serialNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string epinNum {
        get {
            return this.epinNumField;
        }
        set {
            this.epinNumField = value;
        }
    }
    
    /// <remarks/>
    public decimal quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public decimal sellingPrice {
        get {
            return this.sellingPriceField;
        }
        set {
            this.sellingPriceField = value;
        }
    }
    
    /// <remarks/>
    public decimal eipDownPayment {
        get {
            return this.eipDownPaymentField;
        }
        set {
            this.eipDownPaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool eipDownPaymentSpecified {
        get {
            return this.eipDownPaymentFieldSpecified;
        }
        set {
            this.eipDownPaymentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ContractLengthEnum contractTerm {
        get {
            return this.contractTermField;
        }
        set {
            this.contractTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contractTermSpecified {
        get {
            return this.contractTermFieldSpecified;
        }
        set {
            this.contractTermFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool voided {
        get {
            return this.voidedField;
        }
        set {
            this.voidedField = value;
        }
    }
    
    /// <remarks/>
    public int activationReasonId {
        get {
            return this.activationReasonIdField;
        }
        set {
            this.activationReasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool activationReasonIdSpecified {
        get {
            return this.activationReasonIdFieldSpecified;
        }
        set {
            this.activationReasonIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int overrideReasonId {
        get {
            return this.overrideReasonIdField;
        }
        set {
            this.overrideReasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool overrideReasonIdSpecified {
        get {
            return this.overrideReasonIdFieldSpecified;
        }
        set {
            this.overrideReasonIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int returnReasonId {
        get {
            return this.returnReasonIdField;
        }
        set {
            this.returnReasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool returnReasonIdSpecified {
        get {
            return this.returnReasonIdFieldSpecified;
        }
        set {
            this.returnReasonIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string flexCardNumber {
        get {
            return this.flexCardNumberField;
        }
        set {
            this.flexCardNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string flexCardControlNumber {
        get {
            return this.flexCardControlNumberField;
        }
        set {
            this.flexCardControlNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class EipPlanInfo {
    
    private string planDateField;
    
    private string planIdField;
    
    private decimal totalSalesTaxField;
    
    private decimal totalPriceField;
    
    private decimal totalPriceAfterTaxField;
    
    private decimal totalDownPaymentField;
    
    private decimal totalBalanceAmountField;
    
    private decimal totalFinancedAmountField;
    
    private decimal annualPercentageRateField;
    
    private decimal financeChargeField;
    
    private int numberOfMonthlyInstallmentsField;
    
    private decimal totalAmountOfMonthlyInstallmentsField;
    
    private string firstMonthlyInstallmentDueDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string planDate {
        get {
            return this.planDateField;
        }
        set {
            this.planDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string planId {
        get {
            return this.planIdField;
        }
        set {
            this.planIdField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalSalesTax {
        get {
            return this.totalSalesTaxField;
        }
        set {
            this.totalSalesTaxField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalPrice {
        get {
            return this.totalPriceField;
        }
        set {
            this.totalPriceField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalPriceAfterTax {
        get {
            return this.totalPriceAfterTaxField;
        }
        set {
            this.totalPriceAfterTaxField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalDownPayment {
        get {
            return this.totalDownPaymentField;
        }
        set {
            this.totalDownPaymentField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalBalanceAmount {
        get {
            return this.totalBalanceAmountField;
        }
        set {
            this.totalBalanceAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalFinancedAmount {
        get {
            return this.totalFinancedAmountField;
        }
        set {
            this.totalFinancedAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal annualPercentageRate {
        get {
            return this.annualPercentageRateField;
        }
        set {
            this.annualPercentageRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal financeCharge {
        get {
            return this.financeChargeField;
        }
        set {
            this.financeChargeField = value;
        }
    }
    
    /// <remarks/>
    public int numberOfMonthlyInstallments {
        get {
            return this.numberOfMonthlyInstallmentsField;
        }
        set {
            this.numberOfMonthlyInstallmentsField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalAmountOfMonthlyInstallments {
        get {
            return this.totalAmountOfMonthlyInstallmentsField;
        }
        set {
            this.totalAmountOfMonthlyInstallmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string firstMonthlyInstallmentDueDate {
        get {
            return this.firstMonthlyInstallmentDueDateField;
        }
        set {
            this.firstMonthlyInstallmentDueDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CustomerDetail {
    
    private string banField;
    
    private string msisdnField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string companyNameField;
    
    private string homePhoneField;
    
    private string businessPhoneField;
    
    private string faxPhoneField;
    
    private Address addressField;
    
    private ServiceProviderEnum serviceProviderField;
    
    private decimal currentBalanceField;
    
    private bool currentBalanceFieldSpecified;
    
    private decimal pastDueBalanceField;
    
    private bool pastDueBalanceFieldSpecified;
    
    private string accountStatusField;
    
    private string taxExemptionIdField;
    
    private string cycleCloseDayField;
    
    private bool deliquentField;
    
    private string creditClassField;
    
    private AccountTypeEnum accountTypeField;
    
    private bool accountTypeFieldSpecified;
    
    private string billCycleCodeField;
    
    public CustomerDetail() {
        this.serviceProviderField = ServiceProviderEnum.TMobile;
        this.taxExemptionIdField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ban {
        get {
            return this.banField;
        }
        set {
            this.banField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string msisdn {
        get {
            return this.msisdnField;
        }
        set {
            this.msisdnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string companyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string homePhone {
        get {
            return this.homePhoneField;
        }
        set {
            this.homePhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string businessPhone {
        get {
            return this.businessPhoneField;
        }
        set {
            this.businessPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string faxPhone {
        get {
            return this.faxPhoneField;
        }
        set {
            this.faxPhoneField = value;
        }
    }
    
    /// <remarks/>
    public Address address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public ServiceProviderEnum serviceProvider {
        get {
            return this.serviceProviderField;
        }
        set {
            this.serviceProviderField = value;
        }
    }
    
    /// <remarks/>
    public decimal currentBalance {
        get {
            return this.currentBalanceField;
        }
        set {
            this.currentBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool currentBalanceSpecified {
        get {
            return this.currentBalanceFieldSpecified;
        }
        set {
            this.currentBalanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal pastDueBalance {
        get {
            return this.pastDueBalanceField;
        }
        set {
            this.pastDueBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pastDueBalanceSpecified {
        get {
            return this.pastDueBalanceFieldSpecified;
        }
        set {
            this.pastDueBalanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string accountStatus {
        get {
            return this.accountStatusField;
        }
        set {
            this.accountStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string taxExemptionId {
        get {
            return this.taxExemptionIdField;
        }
        set {
            this.taxExemptionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gDay")]
    public string cycleCloseDay {
        get {
            return this.cycleCloseDayField;
        }
        set {
            this.cycleCloseDayField = value;
        }
    }
    
    /// <remarks/>
    public bool deliquent {
        get {
            return this.deliquentField;
        }
        set {
            this.deliquentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string creditClass {
        get {
            return this.creditClassField;
        }
        set {
            this.creditClassField = value;
        }
    }
    
    /// <remarks/>
    public AccountTypeEnum accountType {
        get {
            return this.accountTypeField;
        }
        set {
            this.accountTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool accountTypeSpecified {
        get {
            return this.accountTypeFieldSpecified;
        }
        set {
            this.accountTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gDay")]
    public string billCycleCode {
        get {
            return this.billCycleCodeField;
        }
        set {
            this.billCycleCodeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferencedAddress))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class Address {
    
    private AddressClassificationEnum addressClassificationField;
    
    private bool addressClassificationFieldSpecified;
    
    private string address1Field;
    
    private string address2Field;
    
    private string cityField;
    
    private StateEnum stateField;
    
    private bool stateFieldSpecified;
    
    private string zipCodeField;
    
    private string postalCodeField;
    
    private string zipCodeExtensionField;
    
    private bool internationalField;
    
    private bool internationalFieldSpecified;
    
    private string geoCodeField;
    
    private sbyte uncertaintyIndField;
    
    private bool uncertaintyIndFieldSpecified;
    
    private string latLongField;
    
    private string urbanizationField;
    
    private string countryCodeField;
    
    private string attentionField;
    
    private string addressTypeField;
    
    /// <remarks/>
    public AddressClassificationEnum addressClassification {
        get {
            return this.addressClassificationField;
        }
        set {
            this.addressClassificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool addressClassificationSpecified {
        get {
            return this.addressClassificationFieldSpecified;
        }
        set {
            this.addressClassificationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public StateEnum state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stateSpecified {
        get {
            return this.stateFieldSpecified;
        }
        set {
            this.stateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string zipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string zipCodeExtension {
        get {
            return this.zipCodeExtensionField;
        }
        set {
            this.zipCodeExtensionField = value;
        }
    }
    
    /// <remarks/>
    public bool international {
        get {
            return this.internationalField;
        }
        set {
            this.internationalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool internationalSpecified {
        get {
            return this.internationalFieldSpecified;
        }
        set {
            this.internationalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string geoCode {
        get {
            return this.geoCodeField;
        }
        set {
            this.geoCodeField = value;
        }
    }
    
    /// <remarks/>
    public sbyte uncertaintyInd {
        get {
            return this.uncertaintyIndField;
        }
        set {
            this.uncertaintyIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool uncertaintyIndSpecified {
        get {
            return this.uncertaintyIndFieldSpecified;
        }
        set {
            this.uncertaintyIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string latLong {
        get {
            return this.latLongField;
        }
        set {
            this.latLongField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string urbanization {
        get {
            return this.urbanizationField;
        }
        set {
            this.urbanizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string countryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string attention {
        get {
            return this.attentionField;
        }
        set {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string addressType {
        get {
            return this.addressTypeField;
        }
        set {
            this.addressTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class ReferencedAddress : Address {
    
    private long addressIdField;
    
    private long linkSeqNbrField;
    
    private bool linkSeqNbrFieldSpecified;
    
    /// <remarks/>
    public long addressId {
        get {
            return this.addressIdField;
        }
        set {
            this.addressIdField = value;
        }
    }
    
    /// <remarks/>
    public long linkSeqNbr {
        get {
            return this.linkSeqNbrField;
        }
        set {
            this.linkSeqNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool linkSeqNbrSpecified {
        get {
            return this.linkSeqNbrFieldSpecified;
        }
        set {
            this.linkSeqNbrFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StoreDetail))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class StoreInfo {
    
    private string storeCodeField;
    
    private string storeNameField;
    
    private Address addressField;
    
    private string businessPhoneField;
    
    private string faxNumberField;
    
    private string timeZoneIdField;
    
    private string countyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string storeCode {
        get {
            return this.storeCodeField;
        }
        set {
            this.storeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string storeName {
        get {
            return this.storeNameField;
        }
        set {
            this.storeNameField = value;
        }
    }
    
    /// <remarks/>
    public Address address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string businessPhone {
        get {
            return this.businessPhoneField;
        }
        set {
            this.businessPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string faxNumber {
        get {
            return this.faxNumberField;
        }
        set {
            this.faxNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string timeZoneId {
        get {
            return this.timeZoneIdField;
        }
        set {
            this.timeZoneIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string county {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class StoreDetail : StoreInfo {
    
    private string storeIdField;
    
    private System.DateTime openDateField;
    
    private bool openDateFieldSpecified;
    
    private System.DateTime closeDateField;
    
    private bool closeDateFieldSpecified;
    
    private int divisionField;
    
    private bool divisionFieldSpecified;
    
    private int regionField;
    
    private bool regionFieldSpecified;
    
    private bool isClosedField;
    
    private bool isClosedFieldSpecified;
    
    private bool isStoreAccountableField;
    
    private int storeCreditLevelField;
    
    private string geoCodeField;
    
    private bool isInCityLimitField;
    
    private string companyCodeField;
    
    private LanguageEnum defaultLanguageField;
    
    private string licenseNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string storeId {
        get {
            return this.storeIdField;
        }
        set {
            this.storeIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime openDate {
        get {
            return this.openDateField;
        }
        set {
            this.openDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool openDateSpecified {
        get {
            return this.openDateFieldSpecified;
        }
        set {
            this.openDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime closeDate {
        get {
            return this.closeDateField;
        }
        set {
            this.closeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool closeDateSpecified {
        get {
            return this.closeDateFieldSpecified;
        }
        set {
            this.closeDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int division {
        get {
            return this.divisionField;
        }
        set {
            this.divisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool divisionSpecified {
        get {
            return this.divisionFieldSpecified;
        }
        set {
            this.divisionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool regionSpecified {
        get {
            return this.regionFieldSpecified;
        }
        set {
            this.regionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool isClosed {
        get {
            return this.isClosedField;
        }
        set {
            this.isClosedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isClosedSpecified {
        get {
            return this.isClosedFieldSpecified;
        }
        set {
            this.isClosedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool isStoreAccountable {
        get {
            return this.isStoreAccountableField;
        }
        set {
            this.isStoreAccountableField = value;
        }
    }
    
    /// <remarks/>
    public int storeCreditLevel {
        get {
            return this.storeCreditLevelField;
        }
        set {
            this.storeCreditLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string geoCode {
        get {
            return this.geoCodeField;
        }
        set {
            this.geoCodeField = value;
        }
    }
    
    /// <remarks/>
    public bool isInCityLimit {
        get {
            return this.isInCityLimitField;
        }
        set {
            this.isInCityLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string companyCode {
        get {
            return this.companyCodeField;
        }
        set {
            this.companyCodeField = value;
        }
    }
    
    /// <remarks/>
    public LanguageEnum defaultLanguage {
        get {
            return this.defaultLanguageField;
        }
        set {
            this.defaultLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string licenseNumber {
        get {
            return this.licenseNumberField;
        }
        set {
            this.licenseNumberField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminalKey))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class StoreKey {
    
    private string storeCodeField;
    
    private string operatorIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string storeCode {
        get {
            return this.storeCodeField;
        }
        set {
            this.storeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string operatorId {
        get {
            return this.operatorIdField;
        }
        set {
            this.operatorIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class TerminalKey : StoreKey {
    
    private string networkIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string networkId {
        get {
            return this.networkIdField;
        }
        set {
            this.networkIdField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAgreementDocument))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class Document {
    
    private CustomerDocumentTypeEnum documentTypeField;
    
    private bool documentTypeFieldSpecified;
    
    private byte[] itemField;
    
    /// <remarks/>
    public CustomerDocumentTypeEnum documentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool documentTypeSpecified {
        get {
            return this.documentTypeFieldSpecified;
        }
        set {
            this.documentTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base64EncodedDocumentContent", DataType="base64Binary")]
    public byte[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class ServiceAgreementDocument : Document {
    
    private string documentIDField;
    
    private string banField;
    
    private string msisdnField;
    
    private LanguageEnum agreementLanguageField;
    
    private ServiceAgreementActivityCodeEnum serviceAgreementActivityCodeField;
    
    public ServiceAgreementDocument() {
        this.agreementLanguageField = LanguageEnum.ENGLISH;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string documentID {
        get {
            return this.documentIDField;
        }
        set {
            this.documentIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ban {
        get {
            return this.banField;
        }
        set {
            this.banField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string msisdn {
        get {
            return this.msisdnField;
        }
        set {
            this.msisdnField = value;
        }
    }
    
    /// <remarks/>
    public LanguageEnum agreementLanguage {
        get {
            return this.agreementLanguageField;
        }
        set {
            this.agreementLanguageField = value;
        }
    }
    
    /// <remarks/>
    public ServiceAgreementActivityCodeEnum serviceAgreementActivityCode {
        get {
            return this.serviceAgreementActivityCodeField;
        }
        set {
            this.serviceAgreementActivityCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class ServiceDocument {
    
    private byte[] base64EncodedDocumentContentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] base64EncodedDocumentContent {
        get {
            return this.base64EncodedDocumentContentField;
        }
        set {
            this.base64EncodedDocumentContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CustomerDocument {
    
    private long documentIdField;
    
    private CustomerDocumentTypeEnum documentTypeField;
    
    private ServiceAgreementActivityCodeEnum serviceAgreementActivityCodeField;
    
    private bool serviceAgreementActivityCodeFieldSpecified;
    
    private byte[] pdfFormatField;
    
    /// <remarks/>
    public long documentId {
        get {
            return this.documentIdField;
        }
        set {
            this.documentIdField = value;
        }
    }
    
    /// <remarks/>
    public CustomerDocumentTypeEnum documentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    public ServiceAgreementActivityCodeEnum serviceAgreementActivityCode {
        get {
            return this.serviceAgreementActivityCodeField;
        }
        set {
            this.serviceAgreementActivityCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool serviceAgreementActivityCodeSpecified {
        get {
            return this.serviceAgreementActivityCodeFieldSpecified;
        }
        set {
            this.serviceAgreementActivityCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] pdfFormat {
        get {
            return this.pdfFormatField;
        }
        set {
            this.pdfFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class SaveDocumentRequest : RspRequest {
    
    private ServiceAgreementDocument itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("serviceAgreementDocument")]
    public ServiceAgreementDocument Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CustomerServiceGuideRequest : RspRequest {
    
    private string banField;
    
    private string[] msisdnField;
    
    private LanguageEnum guideLanguageField;
    
    private bool guideColorField;
    
    private bool pooledPlanField;
    
    public CustomerServiceGuideRequest() {
        this.guideLanguageField = LanguageEnum.ENGLISH;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ban {
        get {
            return this.banField;
        }
        set {
            this.banField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("msisdn", DataType="token")]
    public string[] msisdn {
        get {
            return this.msisdnField;
        }
        set {
            this.msisdnField = value;
        }
    }
    
    /// <remarks/>
    public LanguageEnum guideLanguage {
        get {
            return this.guideLanguageField;
        }
        set {
            this.guideLanguageField = value;
        }
    }
    
    /// <remarks/>
    public bool guideColor {
        get {
            return this.guideColorField;
        }
        set {
            this.guideColorField = value;
        }
    }
    
    /// <remarks/>
    public bool pooledPlan {
        get {
            return this.pooledPlanField;
        }
        set {
            this.pooledPlanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CreateEasyPayTermsAndConditionsRequest : RspRequest {
    
    private string banField;
    
    private LanguageEnum docLanguageField;
    
    public CreateEasyPayTermsAndConditionsRequest() {
        this.docLanguageField = LanguageEnum.ENGLISH;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ban {
        get {
            return this.banField;
        }
        set {
            this.banField = value;
        }
    }
    
    /// <remarks/>
    public LanguageEnum docLanguage {
        get {
            return this.docLanguageField;
        }
        set {
            this.docLanguageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CreateEIPDisclosureDocumentRequest : RspRequest {
    
    private TerminalKey terminalKeyField;
    
    private StoreDetail storeDetailField;
    
    private CustomerDetail customerDetailField;
    
    private EipPlanInfo eipPlanInfoField;
    
    private ItemDetailParams[] itemField;
    
    private LanguageEnum languageField;
    
    public CreateEIPDisclosureDocumentRequest() {
        this.languageField = LanguageEnum.ENGLISH;
    }
    
    /// <remarks/>
    public TerminalKey terminalKey {
        get {
            return this.terminalKeyField;
        }
        set {
            this.terminalKeyField = value;
        }
    }
    
    /// <remarks/>
    public StoreDetail storeDetail {
        get {
            return this.storeDetailField;
        }
        set {
            this.storeDetailField = value;
        }
    }
    
    /// <remarks/>
    public CustomerDetail customerDetail {
        get {
            return this.customerDetailField;
        }
        set {
            this.customerDetailField = value;
        }
    }
    
    /// <remarks/>
    public EipPlanInfo eipPlanInfo {
        get {
            return this.eipPlanInfoField;
        }
        set {
            this.eipPlanInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public ItemDetailParams[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public LanguageEnum language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class SaveDocumentResponse : RspResponse {
    
    private string espDocumentIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string espDocumentId {
        get {
            return this.espDocumentIdField;
        }
        set {
            this.espDocumentIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class DocumentResponse : RspResponse {
    
    private Document documentField;
    
    /// <remarks/>
    public Document document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CustomerServiceGuideResponse : RspResponse {
    
    private ServiceDocument serviceDocumentField;
    
    /// <remarks/>
    public ServiceDocument serviceDocument {
        get {
            return this.serviceDocumentField;
        }
        set {
            this.serviceDocumentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retail.tmobile.com/sdo")]
public partial class CustomerDocumentResponse : RspResponse {
    
    private CustomerDocument documentField;
    
    /// <remarks/>
    public CustomerDocument document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void createServiceAgreementCompletedEventHandler(object sender, createServiceAgreementCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createServiceAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createServiceAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CustomerDocumentResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CustomerDocumentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void saveDocumentCompletedEventHandler(object sender, saveDocumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class saveDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal saveDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SaveDocumentResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SaveDocumentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void createEIPDisclosureDocumentCompletedEventHandler(object sender, createEIPDisclosureDocumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createEIPDisclosureDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createEIPDisclosureDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DocumentResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DocumentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void createEasyPayTermsAndConditionsCompletedEventHandler(object sender, createEasyPayTermsAndConditionsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createEasyPayTermsAndConditionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createEasyPayTermsAndConditionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DocumentResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DocumentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getCustomerServiceGuideCompletedEventHandler(object sender, getCustomerServiceGuideCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCustomerServiceGuideCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCustomerServiceGuideCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CustomerServiceGuideResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CustomerServiceGuideResponse)(this.results[0]));
        }
    }
}
}