//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMobileCarrierServiceInterface.Interfaces.RateplanConversionValidation
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using TMobileCarrierServiceInterface.Interfaces.Common;

    // 
    // This source code was auto-generated by wsdl, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "RateplanConversionValidationServiceSOAPBinding", Namespace = "http://retail.tmobile.com/service")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeAndDescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RspRequest))]
    public partial class RateplanConversionValidationService : Microsoft.Web.Services2.WebServicesClientProtocol
    {

        private System.Threading.SendOrPostCallback validateRateplanConversionOperationCompleted;

        /// <remarks/>
        public RateplanConversionValidationService()
        {
            this.Url = "http://localhost:7001/eProxy/service/RateplanConversionValidationService_SOAP_V1";
        }

        /// <remarks/>
        public event validateRateplanConversionCompletedEventHandler validateRateplanConversionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("validateRateplanConversion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("rateplanConversionValidationResponse", Namespace = "http://retail.tmobile.com/sdo")]
        public RateplanConversionValidationResponse validateRateplanConversion([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://retail.tmobile.com/sdo")] RateplanConversionValidationRequest rateplanConversionValidationRequest)
        {
            object[] results = this.Invoke("validateRateplanConversion", new object[] {
                    rateplanConversionValidationRequest});
            return ((RateplanConversionValidationResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginvalidateRateplanConversion(RateplanConversionValidationRequest rateplanConversionValidationRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("validateRateplanConversion", new object[] {
                    rateplanConversionValidationRequest}, callback, asyncState);
        }

        /// <remarks/>
        public RateplanConversionValidationResponse EndvalidateRateplanConversion(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RateplanConversionValidationResponse)(results[0]));
        }

        /// <remarks/>
        public void validateRateplanConversionAsync(RateplanConversionValidationRequest rateplanConversionValidationRequest)
        {
            this.validateRateplanConversionAsync(rateplanConversionValidationRequest, null);
        }

        /// <remarks/>
        public void validateRateplanConversionAsync(RateplanConversionValidationRequest rateplanConversionValidationRequest, object userState)
        {
            if ((this.validateRateplanConversionOperationCompleted == null))
            {
                this.validateRateplanConversionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateRateplanConversionOperationCompleted);
            }
            this.InvokeAsync("validateRateplanConversion", new object[] {
                    rateplanConversionValidationRequest}, this.validateRateplanConversionOperationCompleted, userState);
        }

        private void OnvalidateRateplanConversionOperationCompleted(object arg)
        {
            if ((this.validateRateplanConversionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateRateplanConversionCompleted(this, new validateRateplanConversionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class RateplanConversionValidationRequest : RspRequest
    {

        private RateplanConversionValidationInfo rateplanConversionValidationInfoField;

        /// <remarks/>
        public RateplanConversionValidationInfo rateplanConversionValidationInfo
        {
            get
            {
                return this.rateplanConversionValidationInfoField;
            }
            set
            {
                this.rateplanConversionValidationInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class RateplanConversionValidationInfo
    {

        private string banField;

        private string selectedRateplanField;

        private Service[] selectedServiceField;

        private string marketCodeField;

        private decimal migrationFeeField;

        private bool migrationFeeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string ban
        {
            get
            {
                return this.banField;
            }
            set
            {
                this.banField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string selectedRateplan
        {
            get
            {
                return this.selectedRateplanField;
            }
            set
            {
                this.selectedRateplanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedService")]
        public Service[] selectedService
        {
            get
            {
                return this.selectedServiceField;
            }
            set
            {
                this.selectedServiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string marketCode
        {
            get
            {
                return this.marketCodeField;
            }
            set
            {
                this.marketCodeField = value;
            }
        }

        /// <remarks/>
        public decimal migrationFee
        {
            get
            {
                return this.migrationFeeField;
            }
            set
            {
                this.migrationFeeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool migrationFeeSpecified
        {
            get
            {
                return this.migrationFeeFieldSpecified;
            }
            set
            {
                this.migrationFeeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class Service
    {

        private string socField;

        private string categoryField;

        private string nameField;

        private decimal priceField;

        private bool priceFieldSpecified;

        private string descriptionField;

        private string additionalDescriptionField;

        private ServiceLevel levelField;

        private bool levelFieldSpecified;

        private ServiceClassification serviceClassificationField;

        private ProductType productTypeField;

        private ServiceIdentificationEnum identificationField;

        private bool identificationFieldSpecified;

        private bool contractRequiredField;

        private bool contractRequiredFieldSpecified;

        private System.DateTime contractEndDateField;

        private bool contractEndDateFieldSpecified;

        private FreeIndicatorEnum myFavesIndicatorField;

        private bool myFavesIndicatorFieldSpecified;

        private Attribute[] throttleInfoField;

        public Service()
        {
            this.productTypeField = ProductType.GSM;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string soc
        {
            get
            {
                return this.socField;
            }
            set
            {
                this.socField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string additionalDescription
        {
            get
            {
                return this.additionalDescriptionField;
            }
            set
            {
                this.additionalDescriptionField = value;
            }
        }

        /// <remarks/>
        public ServiceLevel level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified
        {
            get
            {
                return this.levelFieldSpecified;
            }
            set
            {
                this.levelFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ServiceClassification serviceClassification
        {
            get
            {
                return this.serviceClassificationField;
            }
            set
            {
                this.serviceClassificationField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ProductType.GSM)]
        public ProductType productType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }

        /// <remarks/>
        public ServiceIdentificationEnum identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool identificationSpecified
        {
            get
            {
                return this.identificationFieldSpecified;
            }
            set
            {
                this.identificationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool contractRequired
        {
            get
            {
                return this.contractRequiredField;
            }
            set
            {
                this.contractRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractRequiredSpecified
        {
            get
            {
                return this.contractRequiredFieldSpecified;
            }
            set
            {
                this.contractRequiredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime contractEndDate
        {
            get
            {
                return this.contractEndDateField;
            }
            set
            {
                this.contractEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractEndDateSpecified
        {
            get
            {
                return this.contractEndDateFieldSpecified;
            }
            set
            {
                this.contractEndDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public FreeIndicatorEnum myFavesIndicator
        {
            get
            {
                return this.myFavesIndicatorField;
            }
            set
            {
                this.myFavesIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool myFavesIndicatorSpecified
        {
            get
            {
                return this.myFavesIndicatorFieldSpecified;
            }
            set
            {
                this.myFavesIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributes", IsNullable = false)]
        public Attribute[] throttleInfo
        {
            get
            {
                return this.throttleInfoField;
            }
            set
            {
                this.throttleInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://retail.tmobile.com/sdo")]
    public enum ServiceLevel
    {

        /// <remarks/>
        ACCOUNT,

        /// <remarks/>
        SUBSCRIBER,

        /// <remarks/>
        PRODUCT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class ServiceClassification : CodeAndDescription
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceClassification))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class CodeAndDescription
    {

        private string codeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class Attribute
    {

        private string nameField;

        private string unitOfMeasurementField;

        private decimal valueField;

        private bool valueFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string unitOfMeasurement
        {
            get
            {
                return this.unitOfMeasurementField;
            }
            set
            {
                this.unitOfMeasurementField = value;
            }
        }

        /// <remarks/>
        public decimal value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class RateplanConversionValidationResponse : RspResponse
    {

        private RateplanConversionValidationInfo rateplanConversionValidationInfoField;

        private RateplanConversionValidationResponseServiceConflicts[] serviceConflictsField;

        private bool conflictsExistField;

        private bool conflictsExistFieldSpecified;

        /// <remarks/>
        public RateplanConversionValidationInfo rateplanConversionValidationInfo
        {
            get
            {
                return this.rateplanConversionValidationInfoField;
            }
            set
            {
                this.rateplanConversionValidationInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceConflicts")]
        public RateplanConversionValidationResponseServiceConflicts[] serviceConflicts
        {
            get
            {
                return this.serviceConflictsField;
            }
            set
            {
                this.serviceConflictsField = value;
            }
        }

        /// <remarks/>
        public bool conflictsExist
        {
            get
            {
                return this.conflictsExistField;
            }
            set
            {
                this.conflictsExistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conflictsExistSpecified
        {
            get
            {
                return this.conflictsExistFieldSpecified;
            }
            set
            {
                this.conflictsExistFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://retail.tmobile.com/sdo")]
    public partial class RateplanConversionValidationResponseServiceConflicts
    {

        private string msisdnField;

        private string serviceField;

        private string serviceDescriptionField;

        private RateplanConversionValidationResponseServiceConflictsTypeOfConflict typeOfConflictField;

        public RateplanConversionValidationResponseServiceConflicts()
        {
            this.typeOfConflictField = RateplanConversionValidationResponseServiceConflictsTypeOfConflict.SYSTEM;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceDescription
        {
            get
            {
                return this.serviceDescriptionField;
            }
            set
            {
                this.serviceDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RateplanConversionValidationResponseServiceConflictsTypeOfConflict.SYSTEM)]
        public RateplanConversionValidationResponseServiceConflictsTypeOfConflict typeOfConflict
        {
            get
            {
                return this.typeOfConflictField;
            }
            set
            {
                this.typeOfConflictField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void validateRateplanConversionCompletedEventHandler(object sender, validateRateplanConversionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateRateplanConversionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal validateRateplanConversionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RateplanConversionValidationResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RateplanConversionValidationResponse)(this.results[0]));
            }
        }
    }
}