//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMobileCarrierServiceInterface.Interfaces.SubscriberUpdate
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using TMobileCarrierServiceInterface.Interfaces.Common;
    // 
    // This source code was auto-generated by wsdl, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SubscriberUpdateServiceSOAPBinding", Namespace = "http://retail.tmobile.com/service")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RspRequest))]
    public partial class SubscriberUpdateService : Microsoft.Web.Services2.WebServicesClientProtocol
    {

        private System.Threading.SendOrPostCallback extendContractOperationCompleted;

        /// <remarks/>
        public SubscriberUpdateService()
        {
            this.Url = "http://localhost:7001/eProxy/service/SubscriberUpdateService_SOAP_V1";
        }

        /// <remarks/>
        public event extendContractCompletedEventHandler extendContractCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("extendContract", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("renewSubscriberContractResponse", Namespace = "http://retail.tmobile.com/sdo")]
        public RenewSubscriberContractResponse extendContract([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://retail.tmobile.com/sdo")] RenewSubscriberContractRequest renewSubscriberContractRequest)
        {
            object[] results = this.Invoke("extendContract", new object[] {
                    renewSubscriberContractRequest});
            return ((RenewSubscriberContractResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginextendContract(RenewSubscriberContractRequest renewSubscriberContractRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("extendContract", new object[] {
                    renewSubscriberContractRequest}, callback, asyncState);
        }

        /// <remarks/>
        public RenewSubscriberContractResponse EndextendContract(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RenewSubscriberContractResponse)(results[0]));
        }

        /// <remarks/>
        public void extendContractAsync(RenewSubscriberContractRequest renewSubscriberContractRequest)
        {
            this.extendContractAsync(renewSubscriberContractRequest, null);
        }

        /// <remarks/>
        public void extendContractAsync(RenewSubscriberContractRequest renewSubscriberContractRequest, object userState)
        {
            if ((this.extendContractOperationCompleted == null))
            {
                this.extendContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnextendContractOperationCompleted);
            }
            this.InvokeAsync("extendContract", new object[] {
                    renewSubscriberContractRequest}, this.extendContractOperationCompleted, userState);
        }

        private void OnextendContractOperationCompleted(object arg)
        {
            if ((this.extendContractCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.extendContractCompleted(this, new extendContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class RenewSubscriberContractRequest : RspRequest
    {

        private string banField;

        private string msisdnField;

        private System.DateTime contractStartDateField;

        private bool contractStartDateFieldSpecified;

        private ContractLengthEnum contractLengthField;

        private RenewSubscriberContractRequestReasonCode reasonCodeField;

        private string memoTextField;

        private long discountTransactionIdField;

        private bool discountTransactionIdFieldSpecified;

        private bool simOnlyField;

        private bool simOnlyFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string ban
        {
            get
            {
                return this.banField;
            }
            set
            {
                this.banField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime contractStartDate
        {
            get
            {
                return this.contractStartDateField;
            }
            set
            {
                this.contractStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractStartDateSpecified
        {
            get
            {
                return this.contractStartDateFieldSpecified;
            }
            set
            {
                this.contractStartDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ContractLengthEnum contractLength
        {
            get
            {
                return this.contractLengthField;
            }
            set
            {
                this.contractLengthField = value;
            }
        }

        /// <remarks/>
        public RenewSubscriberContractRequestReasonCode reasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string memoText
        {
            get
            {
                return this.memoTextField;
            }
            set
            {
                this.memoTextField = value;
            }
        }

        /// <remarks/>
        public long discountTransactionId
        {
            get
            {
                return this.discountTransactionIdField;
            }
            set
            {
                this.discountTransactionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountTransactionIdSpecified
        {
            get
            {
                return this.discountTransactionIdFieldSpecified;
            }
            set
            {
                this.discountTransactionIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool simOnly
        {
            get
            {
                return this.simOnlyField;
            }
            set
            {
                this.simOnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool simOnlySpecified
        {
            get
            {
                return this.simOnlyFieldSpecified;
            }
            set
            {
                this.simOnlyFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://retail.tmobile.com/sdo")]
    public enum RenewSubscriberContractRequestReasonCode
    {

        /// <remarks/>
        EQU,

        /// <remarks/>
        PPD,

        /// <remarks/>
        MAN,

        /// <remarks/>
        PPC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://retail.tmobile.com/sdo")]
    public partial class RenewSubscriberContractResponse : RspResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void extendContractCompletedEventHandler(object sender, extendContractCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class extendContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal extendContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RenewSubscriberContractResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RenewSubscriberContractResponse)(this.results[0]));
            }
        }
    }
}