//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SprintCarrierServiceInterface.Interfaces.model.doDeactivation
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("fault", Namespace = "http://nextel.com/ovm", IsNullable = false)]
    public partial class OVMFault
    {

        private ErrorInfo[] detailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("errorInfo", IsNullable = false)]
        public ErrorInfo[] detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class ErrorInfo
    {

        private uint errortypeField;

        private string errorcodeField;

        private string errorsubnameField;

        private string errordetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-type")]
        public uint errortype
        {
            get
            {
                return this.errortypeField;
            }
            set
            {
                this.errortypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", DataType = "integer")]
        public string errorcode
        {
            get
            {
                return this.errorcodeField;
            }
            set
            {
                this.errorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-sub-name")]
        public string errorsubname
        {
            get
            {
                return this.errorsubnameField;
            }
            set
            {
                this.errorsubnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-details")]
        public string errordetails
        {
            get
            {
                return this.errordetailsField;
            }
            set
            {
                this.errordetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class DeactivationResponse
    {

        private string nextelorderidField;

        private DeactivationResult resultField;

        private uint billcycledayField;

        private bool billcycledayFieldSpecified;

        private bool terminationfeerequiredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nextel-order-id")]
        public string nextelorderid
        {
            get
            {
                return this.nextelorderidField;
            }
            set
            {
                this.nextelorderidField = value;
            }
        }

        /// <remarks/>
        public DeactivationResult result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bill-cycle-day")]
        public uint billcycleday
        {
            get
            {
                return this.billcycledayField;
            }
            set
            {
                this.billcycledayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool billcycledaySpecified
        {
            get
            {
                return this.billcycledayFieldSpecified;
            }
            set
            {
                this.billcycledayFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("termination-fee-required")]
        public bool terminationfeerequired
        {
            get
            {
                return this.terminationfeerequiredField;
            }
            set
            {
                this.terminationfeerequiredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public enum DeactivationResult
    {

        /// <remarks/>
        DEACTIVATED,

        /// <remarks/>
        CUSTOMER_SAVED,

        /// <remarks/>
        DEACT_NOT_ELIGIBLE,

        /// <remarks/>
        DATA_ERROR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class Address
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("city", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("clone-address", typeof(CloneAddressType))]
        [System.Xml.Serialization.XmlElementAttribute("country-code", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("state-code", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("street-address-1", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("street-address-2", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("update-address", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("zip-code", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public enum CloneAddressType
    {

        /// <remarks/>
        SAME_AS_BILLING,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        city,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("clone-address")]
        cloneaddress,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("country-code")]
        countrycode,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("state-code")]
        statecode,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("street-address-1")]
        streetaddress1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("street-address-2")]
        streetaddress2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("update-address")]
        updateaddress,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("zip-code")]
        zipcode,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class PortIn
    {

        private string portinnumberField;

        private string oldserviceprovidernameField;

        private string oldserviceprovideridField;

        private string oldaccountidField;

        private string oldaccountpasswordField;

        private Name oldaccountnameField;

        private string oldcompanynameField;

        private Address oldaccountaddressField;

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string eligibilityresponsecodeField;

        private string eligibilityresponsedetailsField;

        private string lrnField;

        private bool failedportcontinueField;

        private bool failedportcontinueFieldSpecified;

        private System.DateTime portindateField;

        private bool portindateFieldSpecified;

        private bool manualportindField;

        private bool manualportindFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port-in-number")]
        public string portinnumber
        {
            get
            {
                return this.portinnumberField;
            }
            set
            {
                this.portinnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-service-provider-name")]
        public string oldserviceprovidername
        {
            get
            {
                return this.oldserviceprovidernameField;
            }
            set
            {
                this.oldserviceprovidernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-service-provider-id")]
        public string oldserviceproviderid
        {
            get
            {
                return this.oldserviceprovideridField;
            }
            set
            {
                this.oldserviceprovideridField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-account-id")]
        public string oldaccountid
        {
            get
            {
                return this.oldaccountidField;
            }
            set
            {
                this.oldaccountidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-account-password")]
        public string oldaccountpassword
        {
            get
            {
                return this.oldaccountpasswordField;
            }
            set
            {
                this.oldaccountpasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-account-name")]
        public Name oldaccountname
        {
            get
            {
                return this.oldaccountnameField;
            }
            set
            {
                this.oldaccountnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-company-name")]
        public string oldcompanyname
        {
            get
            {
                return this.oldcompanynameField;
            }
            set
            {
                this.oldcompanynameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-account-address")]
        public Address oldaccountaddress
        {
            get
            {
                return this.oldaccountaddressField;
            }
            set
            {
                this.oldaccountaddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("old-account-federal-tax-id", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("old-account-ssn", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eligibility-response-code")]
        public string eligibilityresponsecode
        {
            get
            {
                return this.eligibilityresponsecodeField;
            }
            set
            {
                this.eligibilityresponsecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eligibility-response-details")]
        public string eligibilityresponsedetails
        {
            get
            {
                return this.eligibilityresponsedetailsField;
            }
            set
            {
                this.eligibilityresponsedetailsField = value;
            }
        }

        /// <remarks/>
        public string lrn
        {
            get
            {
                return this.lrnField;
            }
            set
            {
                this.lrnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failed-port-continue")]
        public bool failedportcontinue
        {
            get
            {
                return this.failedportcontinueField;
            }
            set
            {
                this.failedportcontinueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool failedportcontinueSpecified
        {
            get
            {
                return this.failedportcontinueFieldSpecified;
            }
            set
            {
                this.failedportcontinueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port-in-date", DataType = "date")]
        public System.DateTime portindate
        {
            get
            {
                return this.portindateField;
            }
            set
            {
                this.portindateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portindateSpecified
        {
            get
            {
                return this.portindateFieldSpecified;
            }
            set
            {
                this.portindateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("manual-port-ind")]
        public bool manualportind
        {
            get
            {
                return this.manualportindField;
            }
            set
            {
                this.manualportindField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool manualportindSpecified
        {
            get
            {
                return this.manualportindFieldSpecified;
            }
            set
            {
                this.manualportindFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class Name
    {

        private string sirnameField;

        private string firstnameField;

        private string middleinitialField;

        private string lastnameField;

        private string suffixField;

        private string additionallineField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sir-name")]
        public string sirname
        {
            get
            {
                return this.sirnameField;
            }
            set
            {
                this.sirnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("first-name")]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("middle-initial")]
        public string middleinitial
        {
            get
            {
                return this.middleinitialField;
            }
            set
            {
                this.middleinitialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-name")]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }

        /// <remarks/>
        public string suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additional-line")]
        public string additionalline
        {
            get
            {
                return this.additionallineField;
            }
            set
            {
                this.additionallineField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm", IncludeInSchema = false, TypeName = "doDeactivationItemChoiceType")]
    public enum ItemChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("old-account-federal-tax-id")]
        oldaccountfederaltaxid,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("old-account-ssn")]
        oldaccountssn,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class Phone
    {

        private string hsnField;

        private string simField;

        private string imeiField;

        private string meidField;

        private string macidField;

        private string activationpinField;

        private bool devicecheckField;

        private bool devicecheckFieldSpecified;

        private PortIn portinField;

        private string aliasField;

        private Name unitusernameField;

        private object itemField;

        private string deviceorderkeyField;

        private bool previouslyactivatedField;

        private bool previouslyactivatedFieldSpecified;

        private string idField;

        /// <remarks/>
        public string hsn
        {
            get
            {
                return this.hsnField;
            }
            set
            {
                this.hsnField = value;
            }
        }

        /// <remarks/>
        public string sim
        {
            get
            {
                return this.simField;
            }
            set
            {
                this.simField = value;
            }
        }

        /// <remarks/>
        public string imei
        {
            get
            {
                return this.imeiField;
            }
            set
            {
                this.imeiField = value;
            }
        }

        /// <remarks/>
        public string meid
        {
            get
            {
                return this.meidField;
            }
            set
            {
                this.meidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mac-id")]
        public string macid
        {
            get
            {
                return this.macidField;
            }
            set
            {
                this.macidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activation-pin")]
        public string activationpin
        {
            get
            {
                return this.activationpinField;
            }
            set
            {
                this.activationpinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-check")]
        public bool devicecheck
        {
            get
            {
                return this.devicecheckField;
            }
            set
            {
                this.devicecheckField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool devicecheckSpecified
        {
            get
            {
                return this.devicecheckFieldSpecified;
            }
            set
            {
                this.devicecheckFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port-in")]
        public PortIn portin
        {
            get
            {
                return this.portinField;
            }
            set
            {
                this.portinField = value;
            }
        }

        /// <remarks/>
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit-user-name")]
        public Name unitusername
        {
            get
            {
                return this.unitusernameField;
            }
            set
            {
                this.unitusernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activation-zip-code", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("service-area-address", typeof(Address))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-order-key")]
        public string deviceorderkey
        {
            get
            {
                return this.deviceorderkeyField;
            }
            set
            {
                this.deviceorderkeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("previously-activated")]
        public bool previouslyactivated
        {
            get
            {
                return this.previouslyactivatedField;
            }
            set
            {
                this.previouslyactivatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previouslyactivatedSpecified
        {
            get
            {
                return this.previouslyactivatedFieldSpecified;
            }
            set
            {
                this.previouslyactivatedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public partial class PhoneExtType
    {

        private string extField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ext
        {
            get
            {
                return this.extField;
            }
            set
            {
                this.extField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("requestHeader", Namespace = "http://nextel.com/ovm", IsNullable = false)]
    public partial class RequestMessageHeader
    {

        private string pinField;

        private string vendorcodeField;

        private string subvendorcodeField;

        private string vendorusernameField;

        private string vendorpasswordField;

        private string messageidField;

        private string orderidField;

        private RequestMessageType messagetypeField;

        private System.DateTime timestampField;

        private string returnurlField;

        private string resendnumberField;

        private BrandType brandtypeField;

        private bool brandtypeFieldSpecified;

        private string storeidField;

        private string associateidField;

        /// <remarks/>
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-code")]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sub-vendor-code")]
        public string subvendorcode
        {
            get
            {
                return this.subvendorcodeField;
            }
            set
            {
                this.subvendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-username")]
        public string vendorusername
        {
            get
            {
                return this.vendorusernameField;
            }
            set
            {
                this.vendorusernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-password")]
        public string vendorpassword
        {
            get
            {
                return this.vendorpasswordField;
            }
            set
            {
                this.vendorpasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid
        {
            get
            {
                return this.messageidField;
            }
            set
            {
                this.messageidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-id")]
        public string orderid
        {
            get
            {
                return this.orderidField;
            }
            set
            {
                this.orderidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-type")]
        public RequestMessageType messagetype
        {
            get
            {
                return this.messagetypeField;
            }
            set
            {
                this.messagetypeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("return-url", DataType = "anyURI")]
        public string returnurl
        {
            get
            {
                return this.returnurlField;
            }
            set
            {
                this.returnurlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resend-number", DataType = "nonNegativeInteger")]
        public string resendnumber
        {
            get
            {
                return this.resendnumberField;
            }
            set
            {
                this.resendnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-type")]
        public BrandType brandtype
        {
            get
            {
                return this.brandtypeField;
            }
            set
            {
                this.brandtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brandtypeSpecified
        {
            get
            {
                return this.brandtypeFieldSpecified;
            }
            set
            {
                this.brandtypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("store-id")]
        public string storeid
        {
            get
            {
                return this.storeidField;
            }
            set
            {
                this.storeidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associate-id")]
        public string associateid
        {
            get
            {
                return this.associateidField;
            }
            set
            {
                this.associateidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public enum RequestMessageType
    {

        /// <remarks/>
        ACTIVATION_REQUEST,

        /// <remarks/>
        ACTIVATE_NOW_REQUEST,

        /// <remarks/>
        CREDIT_CHECK_REQUEST,

        /// <remarks/>
        DEACTIVATION_REQUEST,

        /// <remarks/>
        PORT_ELIGIBILITY_REQUEST,

        /// <remarks/>
        VALIDATION_REQUEST,

        /// <remarks/>
        PORT_STATUS_REQUEST,

        /// <remarks/>
        NPA_NXX_REQUEST,

        /// <remarks/>
        ACCOUNT_VALIDATION_REQUEST,

        /// <remarks/>
        CREDIT_CANCEL_REQUEST,

        /// <remarks/>
        PRE_AUTHORIZATION_REQUEST,

        /// <remarks/>
        PLANS_REQUEST,

        /// <remarks/>
        OPTIONS_REQUEST,

        /// <remarks/>
        BILL_SUMMARY_REQUEST,

        /// <remarks/>
        SERVICE_VALIDATION_REQUEST,

        /// <remarks/>
        SECURITY_QUESTION_REQUEST,

        /// <remarks/>
        INVENTORY_CHECK_REQUEST,

        /// <remarks/>
        AUTHENTICATE_RESEND_PIN_REQUEST,

        /// <remarks/>
        COVERAGE_CHECK_REQUEST,

        /// <remarks/>
        CORPORATE_DISCOUNT_REQUEST,

        /// <remarks/>
        ACTIVATE_RESERVED_DEVICE_REQUEST,

        /// <remarks/>
        DEVICE_INFO_REQUEST,

        /// <remarks/>
        ORDER_STATUS_REQUEST,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public enum BrandType
    {

        /// <remarks/>
        NX,

        /// <remarks/>
        SP,

        /// <remarks/>
        HB,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("responseHeader", Namespace = "http://nextel.com/ovm", IsNullable = false)]
    public partial class ResponseMessageHeader
    {

        private string vendorcodeField;

        private string messageidField;

        private string orderidField;

        private ResponseMessageType messagetypeField;

        private System.DateTime timestampField;

        private string resendnumberField;

        private ResponseMessageHeaderBrandtype brandtypeField;

        private bool brandtypeFieldSpecified;

        private string storeidField;

        private string associateidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vendor-code")]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid
        {
            get
            {
                return this.messageidField;
            }
            set
            {
                this.messageidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-id")]
        public string orderid
        {
            get
            {
                return this.orderidField;
            }
            set
            {
                this.orderidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-type")]
        public ResponseMessageType messagetype
        {
            get
            {
                return this.messagetypeField;
            }
            set
            {
                this.messagetypeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resend-number", DataType = "nonNegativeInteger")]
        public string resendnumber
        {
            get
            {
                return this.resendnumberField;
            }
            set
            {
                this.resendnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-type")]
        public ResponseMessageHeaderBrandtype brandtype
        {
            get
            {
                return this.brandtypeField;
            }
            set
            {
                this.brandtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brandtypeSpecified
        {
            get
            {
                return this.brandtypeFieldSpecified;
            }
            set
            {
                this.brandtypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("store-id")]
        public string storeid
        {
            get
            {
                return this.storeidField;
            }
            set
            {
                this.storeidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associate-id")]
        public string associateid
        {
            get
            {
                return this.associateidField;
            }
            set
            {
                this.associateidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public enum ResponseMessageType
    {

        /// <remarks/>
        ACTIVATION_RESPONSE,

        /// <remarks/>
        ACTIVATE_NOW_RESPONSE,

        /// <remarks/>
        CREDIT_CHECK_RESPONSE,

        /// <remarks/>
        DEACTIVATION_RESPONSE,

        /// <remarks/>
        PARSE_RESPONSE,

        /// <remarks/>
        CANCELLED_RESPONSE,

        /// <remarks/>
        STATUS_RESPONSE,

        /// <remarks/>
        PORT_ELIGIBILITY_RESPONSE,

        /// <remarks/>
        VALIDATION_RESPONSE,

        /// <remarks/>
        PORT_STATUS_RESPONSE,

        /// <remarks/>
        NPA_NXX_RESPONSE,

        /// <remarks/>
        ACCOUNT_VALIDATION_RESPONSE,

        /// <remarks/>
        CREDIT_CANCEL_RESPONSE,

        /// <remarks/>
        PRE_AUTHORIZATION_RESPONSE,

        /// <remarks/>
        PLANS_RESPONSE,

        /// <remarks/>
        OPTIONS_RESPONSE,

        /// <remarks/>
        BILL_SUMMARY_RESPONSE,

        /// <remarks/>
        SERVICE_VALIDATION_RESPONSE,

        /// <remarks/>
        SECURITY_QUESTION_RESPONSE,

        /// <remarks/>
        INVENTORY_CHECK_RESPONSE,

        /// <remarks/>
        AUTHENTICATE_RESEND_PIN_RESPONSE,

        /// <remarks/>
        COVERAGE_CHECK_RESPONSE,

        /// <remarks/>
        CORPORATE_DISCOUNT_RESPONSE,

        /// <remarks/>
        ACTIVATE_RESERVED_DEVICE_RESPONSE,

        /// <remarks/>
        DEVICE_INFO_RESPONSE,

        /// <remarks/>
        ORDER_STATUS_RESPONSE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://nextel.com/ovm")]
    public enum ResponseMessageHeaderBrandtype
    {

        /// <remarks/>
        NX,

        /// <remarks/>
        SP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("ackResponse", Namespace = "http://nextel.com/ovm", IsNullable = false)]
    public partial class ParseResponse
    {

        private ParseResponseType parseresultField;

        private string detailsField;

        private string sprintorderidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parse-result")]
        public ParseResponseType parseresult
        {
            get
            {
                return this.parseresultField;
            }
            set
            {
                this.parseresultField = value;
            }
        }

        /// <remarks/>
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sprint-order-id")]
        public string sprintorderid
        {
            get
            {
                return this.sprintorderidField;
            }
            set
            {
                this.sprintorderidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    public enum ParseResponseType
    {

        /// <remarks/>
        ACK,

        /// <remarks/>
        NACK,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("doDeactivation", Namespace = "http://nextel.com/ovm", IsNullable = false)]
    public partial class DeactivationRequest
    {

        private string referencenextelorderidField;

        private bool equipreturnedField;

        private System.DateTime activationdateField;

        private System.DateTime returndateField;

        private Name nameField;

        private string homephoneField;

        private PhoneExtType workphoneField;

        private Phone phoneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference-nextel-order-id")]
        public string referencenextelorderid
        {
            get
            {
                return this.referencenextelorderidField;
            }
            set
            {
                this.referencenextelorderidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("equip-returned")]
        public bool equipreturned
        {
            get
            {
                return this.equipreturnedField;
            }
            set
            {
                this.equipreturnedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activation-date")]
        public System.DateTime activationdate
        {
            get
            {
                return this.activationdateField;
            }
            set
            {
                this.activationdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("return-date")]
        public System.DateTime returndate
        {
            get
            {
                return this.returndateField;
            }
            set
            {
                this.returndateField = value;
            }
        }

        /// <remarks/>
        public Name name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("home-phone")]
        public string homephone
        {
            get
            {
                return this.homephoneField;
            }
            set
            {
                this.homephoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("work-phone")]
        public PhoneExtType workphone
        {
            get
            {
                return this.workphoneField;
            }
            set
            {
                this.workphoneField = value;
            }
        }

        /// <remarks/>
        public Phone phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://nextel.com/ovm")]
    [System.Xml.Serialization.XmlRootAttribute("doDeactivationResponse", Namespace = "http://nextel.com/ovm", IsNullable = false)]
    public partial class DeactivationServiceResponse
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ackNackResponse", typeof(ParseResponse))]
        [System.Xml.Serialization.XmlElementAttribute("deactivationResponse", typeof(DeactivationResponse))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
}